/**
 * \file
 * \brief Header file which defines GXM variables and functions
 *
 * Copyright (C) 2015 PSP2SDK Project
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#ifndef _PSP2_GXM_
#define _PSP2_GXM_

#include <psp2/types.h>

#ifdef __cplusplus
extern "C" {
#endif

// Error Codes

enum {
	PSP2_GXM_ERROR_UNINITIALIZED	= 0x805B0000,
	PSP2_GXM_ERROR_ALREADY_INITIALIZED	= 0x805B0001,
	PSP2_GXM_ERROR_OUT_OF_MEMORY	= 0x805B0002,
	PSP2_GXM_ERROR_INVALID_VALUE	= 0x805B0003,
	PSP2_GXM_ERROR_INVALID_POINTER	= 0x805B0004,
	PSP2_GXM_ERROR_INVALID_ALIGNMENT	= 0x805B0005,
	PSP2_GXM_ERROR_NOT_WITHIN_SCENE	= 0x805B0006,
	PSP2_GXM_ERROR_WITHIN_SCENE	= 0x805B0007,
	PSP2_GXM_ERROR_NULL_PROGRAM	= 0x805B0008,
	PSP2_GXM_ERROR_UNSUPPORTED	= 0x805B0009,
	PSP2_GXM_ERROR_PATCHER_INTERNAL	= 0x805B000A,
	PSP2_GXM_ERROR_RESERVE_FAILED	= 0x805B000B,
	PSP2_GXM_ERROR_PROGRAM_IN_USE	= 0x805B000C,
	PSP2_GXM_ERROR_INVALID_INDEX_COUNT	= 0x805B000D,
	PSP2_GXM_ERROR_INVALID_POLYGON_MODE	= 0x805B000E,
	PSP2_GXM_ERROR_INVALID_SAMPLER_RESULT_TYPE_PRECISION	= 0x805B000F,
	PSP2_GXM_ERROR_INVALID_SAMPLER_RESULT_TYPE_COMPONENT_COUNT	= 0x805B0010,
	PSP2_GXM_ERROR_UNIFORM_BUFFER_NOT_RESERVED	= 0x805B0011,
	PSP2_GXM_ERROR_INVALID_AUXILIARY_SURFACE	= 0x805B0013,
	PSP2_GXM_ERROR_INVALID_PRECOMPUTED_DRAW	= 0x805B0014,
	PSP2_GXM_ERROR_INVALID_PRECOMPUTED_VERTEX_STATE	= 0x805B0015,
	PSP2_GXM_ERROR_INVALID_PRECOMPUTED_FRAGMENT_STATE	= 0x805B0016,
	PSP2_GXM_ERROR_DRIVER	= 0x805B0017
};

typedef void (SceGxmDisplayQueueCallback)(const void *callbackData);

typedef struct SceGxmInitializeParams {
	unsigned int flags;
	unsigned int displayQueueMaxPendingCount;
	SceGxmDisplayQueueCallback *displayQueueCallback;
	unsigned int displayQueueCallbackDataSize;
	SceSize parameterBufferSize;
} SceGxmInitializeParams;

typedef enum SceGxmMemoryAttribFlags {
	PSP2_GXM_MEMORY_ATTRIB_READ	= 1,
	PSP2_GXM_MEMORY_ATTRIB_WRITE	= 2,
	PSP2_GXM_MEMORY_ATTRIB_RW	= (PSP2_GXM_MEMORY_ATTRIB_READ | PSP2_GXM_MEMORY_ATTRIB_WRITE)
} SceGxmMemoryAttribFlags;

typedef enum SceGxmAttributeFormat {
	PSP2_GXM_ATTRIBUTE_FORMAT_U8,
	PSP2_GXM_ATTRIBUTE_FORMAT_S8,
	PSP2_GXM_ATTRIBUTE_FORMAT_U16,
	PSP2_GXM_ATTRIBUTE_FORMAT_S16,
	PSP2_GXM_ATTRIBUTE_FORMAT_U8N,
	PSP2_GXM_ATTRIBUTE_FORMAT_S8N,
	PSP2_GXM_ATTRIBUTE_FORMAT_U16N,
	PSP2_GXM_ATTRIBUTE_FORMAT_S16N,
	PSP2_GXM_ATTRIBUTE_FORMAT_F16,
	PSP2_GXM_ATTRIBUTE_FORMAT_F32
} SceGxmAttributeFormat;

typedef enum SceGxmDepthStencilFormat {
	PSP2_GXM_DEPTH_STENCIL_FORMAT_DF32	= 0x00044000u,
	PSP2_GXM_DEPTH_STENCIL_FORMAT_S8	= 0x00022000u,
	PSP2_GXM_DEPTH_STENCIL_FORMAT_DF32_S8	= 0x00066000u,
	PSP2_GXM_DEPTH_STENCIL_FORMAT_S8D24	= 0x01266000u,
	PSP2_GXM_DEPTH_STENCIL_FORMAT_D16	= 0x02444000u
} SceGxmDepthStencilFormat;

typedef enum SceGxmPrimitiveType {
	PSP2_GXM_PRIMITIVE_TRIANGLES	= 0x00000000u,
	PSP2_GXM_PRIMITIVE_LINES	= 0x04000000u,
	PSP2_GXM_PRIMITIVE_POINTS	= 0x08000000u,
	PSP2_GXM_PRIMITIVE_TRIANGLE_STRIP	= 0x0c000000u,
	PSP2_GXM_PRIMITIVE_TRIANGLE_FAN	= 0x10000000u,
	PSP2_GXM_PRIMITIVE_TRIANGLE_EDGES	= 0x14000000u
} SceGxmPrimitiveType;

typedef enum SceGxmEdgeEnableFlags {
	PSP2_GXM_EDGE_ENABLE_01	= 0x00000100u,
	PSP2_GXM_EDGE_ENABLE_12	= 0x00000200u,
	PSP2_GXM_EDGE_ENABLE_20	= 0x00000400u
} SceGxmEdgeEnableFlags;

typedef enum SceGxmRegionClipMode {
	PSP2_GXM_REGION_CLIP_NONE	= 0x00000000u,
	PSP2_GXM_REGION_CLIP_ALL	= 0x40000000u,
	PSP2_GXM_REGION_CLIP_OUTSIDE	= 0x80000000u,
	PSP2_GXM_REGION_CLIP_INSIDE	= 0xc0000000u
} SceGxmRegionClipMode;

typedef enum SceGxmDepthFunc {
	PSP2_GXM_DEPTH_FUNC_NEVER	= 0x00000000u,
	PSP2_GXM_DEPTH_FUNC_LESS	= 0x00400000u,
	PSP2_GXM_DEPTH_FUNC_EQUAL	= 0x00800000u,
	PSP2_GXM_DEPTH_FUNC_LESS_EQUAL	= 0x00c00000u,
	PSP2_GXM_DEPTH_FUNC_GREATER	= 0x01000000u,
	PSP2_GXM_DEPTH_FUNC_NOT_EQUAL	= 0x01400000u,
	PSP2_GXM_DEPTH_FUNC_GREATER_EQUAL	= 0x01800000u,
	PSP2_GXM_DEPTH_FUNC_ALWAYS	= 0x01c00000u
} SceGxmDepthFunc;

typedef enum SceGxmStencilFunc {
	PSP2_GXM_STENCIL_FUNC_NEVER	= 0x00000000u,
	PSP2_GXM_STENCIL_FUNC_LESS	= 0x02000000u,
	PSP2_GXM_STENCIL_FUNC_EQUAL	= 0x04000000u,
	PSP2_GXM_STENCIL_FUNC_LESS_EQUAL	= 0x06000000u,
	PSP2_GXM_STENCIL_FUNC_GREATER	= 0x08000000u,
	PSP2_GXM_STENCIL_FUNC_NOT_EQUAL	= 0x0a000000u,
	PSP2_GXM_STENCIL_FUNC_GREATER_EQUAL	= 0x0c000000u,
	PSP2_GXM_STENCIL_FUNC_ALWAYS	= 0x0e000000u
} SceGxmStencilFunc;

typedef enum SceGxmStencilOp {
	PSP2_GXM_STENCIL_OP_KEEP	= 0x00000000u,
	PSP2_GXM_STENCIL_OP_ZERO	= 0x00000001u,
	PSP2_GXM_STENCIL_OP_REPLACE	= 0x00000002u,
	PSP2_GXM_STENCIL_OP_INCR	= 0x00000003u,
	PSP2_GXM_STENCIL_OP_DECR	= 0x00000004u,
	PSP2_GXM_STENCIL_OP_INVERT	= 0x00000005u,
	PSP2_GXM_STENCIL_OP_INCR_WRAP	= 0x00000006u,
	PSP2_GXM_STENCIL_OP_DECR_WRAP	= 0x00000007u
} SceGxmStencilOp;

typedef enum SceGxmCullMode {
	PSP2_GXM_CULL_NONE	= 0x00000000u,
	PSP2_GXM_CULL_CW	= 0x00000001u,
	PSP2_GXM_CULL_CCW	= 0x00000002u
} SceGxmCullMode;

typedef enum SceGxmPolygonMode {
	PSP2_GXM_POLYGON_MODE_TRIANGLE_FILL	= 0x00000000u,
	PSP2_GXM_POLYGON_MODE_LINE	= 0x00008000u,
	PSP2_GXM_POLYGON_MODE_POINT_10UV	= 0x00010000u,
	PSP2_GXM_POLYGON_MODE_POINT	= 0x00018000u,
	PSP2_GXM_POLYGON_MODE_POINT_01UV	= 0x00020000u,
	PSP2_GXM_POLYGON_MODE_TRIANGLE_LINE	= 0x00028000u,
	PSP2_GXM_POLYGON_MODE_TRIANGLE_POINT	= 0x00030000u
} SceGxmPolygonMode;

typedef enum SceGxmColorSwizzle4Mode {
	PSP2_GXM_COLOR_SWIZZLE4_ABGR	= 0x00000000u,
	PSP2_GXM_COLOR_SWIZZLE4_ARGB	= 0x00100000u,
	PSP2_GXM_COLOR_SWIZZLE4_RGBA	= 0x00200000u,
	PSP2_GXM_COLOR_SWIZZLE4_BGRA	= 0x00300000u
} SceGxmColorSwizzle4Mode;

typedef enum SceGxmColorSwizzle3Mode {
	PSP2_GXM_COLOR_SWIZZLE3_BGR	= 0x00000000u,
	PSP2_GXM_COLOR_SWIZZLE3_RGB	= 0x00100000u
} SceGxmColorSwizzle3Mode;

typedef enum SceGxmColorSwizzle2Mode {
	PSP2_GXM_COLOR_SWIZZLE2_GR	= 0x00000000u,
	PSP2_GXM_COLOR_SWIZZLE2_RG	= 0x00100000u,
	PSP2_GXM_COLOR_SWIZZLE2_RA	= 0x00200000u,
	PSP2_GXM_COLOR_SWIZZLE2_AR = 0x00300000u
} SceGxmColorSwizzle2Mode;

typedef enum SceGxmColorSwizzle1Mode {
	PSP2_GXM_COLOR_SWIZZLE1_R	= 0x00000000u,
	PSP2_GXM_COLOR_SWIZZLE1_G	= 0x00100000u,
	PSP2_GXM_COLOR_SWIZZLE1_A	= 0x00100000u
} SceGxmColorSwizzle1Mode;

typedef enum SceGxmColorBaseFormat {
	PSP2_GXM_COLOR_BASE_FORMAT_U8U8U8U8	= 0x00000000,
	PSP2_GXM_COLOR_BASE_FORMAT_U8U8U8	= 0x10000000,
	PSP2_GXM_COLOR_BASE_FORMAT_U5U6U5	= 0x30000000,
	PSP2_GXM_COLOR_BASE_FORMAT_U1U5U5U5	= 0x40000000,
	PSP2_GXM_COLOR_BASE_FORMAT_U4U4U4U4	= 0x50000000,
	PSP2_GXM_COLOR_BASE_FORMAT_U8U3U3U2	= 0x60000000,
	PSP2_GXM_COLOR_BASE_FORMAT_F16	= 0xf0000000,
	PSP2_GXM_COLOR_BASE_FORMAT_F16F16	= 0x00800000,
	PSP2_GXM_COLOR_BASE_FORMAT_F32	= 0x10800000,
	PSP2_GXM_COLOR_BASE_FORMAT_S16	= 0x20800000,
	PSP2_GXM_COLOR_BASE_FORMAT_S16S16	= 0x30800000,
	PSP2_GXM_COLOR_BASE_FORMAT_U16	= 0x40800000,
	PSP2_GXM_COLOR_BASE_FORMAT_U16U16	= 0x50800000,
	PSP2_GXM_COLOR_BASE_FORMAT_U2U10U10U10	= 0x60800000,
	PSP2_GXM_COLOR_BASE_FORMAT_U8	= 0x80800000,
	PSP2_GXM_COLOR_BASE_FORMAT_S8	= 0x90800000,
	PSP2_GXM_COLOR_BASE_FORMAT_S5S5U6	= 0xa0800000,
	PSP2_GXM_COLOR_BASE_FORMAT_U8U8	= 0xb0800000,
	PSP2_GXM_COLOR_BASE_FORMAT_S8S8	= 0xc0800000,
	PSP2_GXM_COLOR_BASE_FORMAT_U8S8S8U8	= 0xd0800000,
	PSP2_GXM_COLOR_BASE_FORMAT_S8S8S8S8	= 0xe0800000,
	PSP2_GXM_COLOR_BASE_FORMAT_F16F16F16F16	= 0x01000000,
	PSP2_GXM_COLOR_BASE_FORMAT_F32F32	= 0x11000000,
	PSP2_GXM_COLOR_BASE_FORMAT_F11F11F10	= 0x21000000,
	PSP2_GXM_COLOR_BASE_FORMAT_SE5M9M9M9	= 0x31000000,
	PSP2_GXM_COLOR_BASE_FORMAT_U2F10F10F10	= 0x41000000
} SceGxmColorBaseFormat;

typedef enum SceGxmColorFormat {
	// Supported formats

	PSP2_GXM_COLOR_FORMAT_U8U8U8U8_ABGR = PSP2_GXM_COLOR_BASE_FORMAT_U8U8U8U8 | PSP2_GXM_COLOR_SWIZZLE4_ABGR,
	PSP2_GXM_COLOR_FORMAT_U8U8U8U8_ARGB = PSP2_GXM_COLOR_BASE_FORMAT_U8U8U8U8 | PSP2_GXM_COLOR_SWIZZLE4_ARGB,
	PSP2_GXM_COLOR_FORMAT_U8U8U8U8_RGBA = PSP2_GXM_COLOR_BASE_FORMAT_U8U8U8U8 | PSP2_GXM_COLOR_SWIZZLE4_RGBA,
	PSP2_GXM_COLOR_FORMAT_U8U8U8U8_BGRA = PSP2_GXM_COLOR_BASE_FORMAT_U8U8U8U8 | PSP2_GXM_COLOR_SWIZZLE4_BGRA,

	PSP2_GXM_COLOR_FORMAT_U8U8U8_BGR = PSP2_GXM_COLOR_BASE_FORMAT_U8U8U8 | PSP2_GXM_COLOR_SWIZZLE3_BGR,
	PSP2_GXM_COLOR_FORMAT_U8U8U8_RGB = PSP2_GXM_COLOR_BASE_FORMAT_U8U8U8 | PSP2_GXM_COLOR_SWIZZLE3_RGB,

	PSP2_GXM_COLOR_FORMAT_U5U6U5_BGR = PSP2_GXM_COLOR_BASE_FORMAT_U5U6U5 | PSP2_GXM_COLOR_SWIZZLE3_BGR,
	PSP2_GXM_COLOR_FORMAT_U5U6U5_RGB = PSP2_GXM_COLOR_BASE_FORMAT_U5U6U5 | PSP2_GXM_COLOR_SWIZZLE3_RGB,

	PSP2_GXM_COLOR_FORMAT_U1U5U5U5_ABGR = PSP2_GXM_COLOR_BASE_FORMAT_U1U5U5U5 | PSP2_GXM_COLOR_SWIZZLE4_ABGR,
	PSP2_GXM_COLOR_FORMAT_U1U5U5U5_ARGB = PSP2_GXM_COLOR_BASE_FORMAT_U1U5U5U5 | PSP2_GXM_COLOR_SWIZZLE4_ARGB,
	PSP2_GXM_COLOR_FORMAT_U5U5U5U1_RGBA = PSP2_GXM_COLOR_BASE_FORMAT_U1U5U5U5 | PSP2_GXM_COLOR_SWIZZLE4_RGBA,
	PSP2_GXM_COLOR_FORMAT_U5U5U5U1_BGRA = PSP2_GXM_COLOR_BASE_FORMAT_U1U5U5U5 | PSP2_GXM_COLOR_SWIZZLE4_BGRA,

	PSP2_GXM_COLOR_FORMAT_U4U4U4U4_ABGR = PSP2_GXM_COLOR_BASE_FORMAT_U4U4U4U4 | PSP2_GXM_COLOR_SWIZZLE4_ABGR,
	PSP2_GXM_COLOR_FORMAT_U4U4U4U4_ARGB = PSP2_GXM_COLOR_BASE_FORMAT_U4U4U4U4 | PSP2_GXM_COLOR_SWIZZLE4_ARGB,
	PSP2_GXM_COLOR_FORMAT_U4U4U4U4_RGBA = PSP2_GXM_COLOR_BASE_FORMAT_U4U4U4U4 | PSP2_GXM_COLOR_SWIZZLE4_RGBA,
	PSP2_GXM_COLOR_FORMAT_U4U4U4U4_BGRA = PSP2_GXM_COLOR_BASE_FORMAT_U4U4U4U4 | PSP2_GXM_COLOR_SWIZZLE4_BGRA,

	PSP2_GXM_COLOR_FORMAT_U8U3U3U2_ARGB = PSP2_GXM_COLOR_BASE_FORMAT_U8U3U3U2,

	PSP2_GXM_COLOR_FORMAT_F16_R = PSP2_GXM_COLOR_BASE_FORMAT_F16 | PSP2_GXM_COLOR_SWIZZLE1_R,
	PSP2_GXM_COLOR_FORMAT_F16_G = PSP2_GXM_COLOR_BASE_FORMAT_F16 | PSP2_GXM_COLOR_SWIZZLE1_G,

	PSP2_GXM_COLOR_FORMAT_F16F16_GR = PSP2_GXM_COLOR_BASE_FORMAT_F16F16 | PSP2_GXM_COLOR_SWIZZLE2_GR,
	PSP2_GXM_COLOR_FORMAT_F16F16_RG = PSP2_GXM_COLOR_BASE_FORMAT_F16F16 | PSP2_GXM_COLOR_SWIZZLE2_RG,

	PSP2_GXM_COLOR_FORMAT_F32_R = PSP2_GXM_COLOR_BASE_FORMAT_F32 | PSP2_GXM_COLOR_SWIZZLE1_R,

	PSP2_GXM_COLOR_FORMAT_S16_R = PSP2_GXM_COLOR_BASE_FORMAT_S16 | PSP2_GXM_COLOR_SWIZZLE1_R,
	PSP2_GXM_COLOR_FORMAT_S16_G = PSP2_GXM_COLOR_BASE_FORMAT_S16 | PSP2_GXM_COLOR_SWIZZLE1_G,

	PSP2_GXM_COLOR_FORMAT_S16S16_GR = PSP2_GXM_COLOR_BASE_FORMAT_S16S16 | PSP2_GXM_COLOR_SWIZZLE2_GR,
	PSP2_GXM_COLOR_FORMAT_S16S16_RG = PSP2_GXM_COLOR_BASE_FORMAT_S16S16 | PSP2_GXM_COLOR_SWIZZLE2_RG,

	PSP2_GXM_COLOR_FORMAT_U16_R = PSP2_GXM_COLOR_BASE_FORMAT_U16 | PSP2_GXM_COLOR_SWIZZLE1_R,
	PSP2_GXM_COLOR_FORMAT_U16_G = PSP2_GXM_COLOR_BASE_FORMAT_U16 | PSP2_GXM_COLOR_SWIZZLE1_G,

	PSP2_GXM_COLOR_FORMAT_U16U16_GR = PSP2_GXM_COLOR_BASE_FORMAT_U16U16 | PSP2_GXM_COLOR_SWIZZLE2_GR,
	PSP2_GXM_COLOR_FORMAT_U16U16_RG = PSP2_GXM_COLOR_BASE_FORMAT_U16U16 | PSP2_GXM_COLOR_SWIZZLE2_RG,

	PSP2_GXM_COLOR_FORMAT_U2U10U10U10_ABGR = PSP2_GXM_COLOR_BASE_FORMAT_U2U10U10U10 | PSP2_GXM_COLOR_SWIZZLE4_ABGR,
	PSP2_GXM_COLOR_FORMAT_U2U10U10U10_ARGB = PSP2_GXM_COLOR_BASE_FORMAT_U2U10U10U10 | PSP2_GXM_COLOR_SWIZZLE4_ARGB,
	PSP2_GXM_COLOR_FORMAT_U10U10U10U2_RGBA = PSP2_GXM_COLOR_BASE_FORMAT_U2U10U10U10 | PSP2_GXM_COLOR_SWIZZLE4_RGBA,
	PSP2_GXM_COLOR_FORMAT_U10U10U10U2_BGRA = PSP2_GXM_COLOR_BASE_FORMAT_U2U10U10U10 | PSP2_GXM_COLOR_SWIZZLE4_BGRA,

	PSP2_GXM_COLOR_FORMAT_U8_R = PSP2_GXM_COLOR_BASE_FORMAT_U8 | PSP2_GXM_COLOR_SWIZZLE1_R,
	PSP2_GXM_COLOR_FORMAT_U8_A = PSP2_GXM_COLOR_BASE_FORMAT_U8 | PSP2_GXM_COLOR_SWIZZLE1_A,

	PSP2_GXM_COLOR_FORMAT_S8_R = PSP2_GXM_COLOR_BASE_FORMAT_S8 | PSP2_GXM_COLOR_SWIZZLE1_R,
	PSP2_GXM_COLOR_FORMAT_S8_A = PSP2_GXM_COLOR_BASE_FORMAT_S8 | PSP2_GXM_COLOR_SWIZZLE1_A,

	PSP2_GXM_COLOR_FORMAT_U6S5S5_BGR = PSP2_GXM_COLOR_BASE_FORMAT_S5S5U6 | PSP2_GXM_COLOR_SWIZZLE3_BGR,
	PSP2_GXM_COLOR_FORMAT_S5S5U6_RGB = PSP2_GXM_COLOR_BASE_FORMAT_S5S5U6 | PSP2_GXM_COLOR_SWIZZLE3_RGB,

	PSP2_GXM_COLOR_FORMAT_U8U8_GR = PSP2_GXM_COLOR_BASE_FORMAT_U8U8 | PSP2_GXM_COLOR_SWIZZLE2_GR,
	PSP2_GXM_COLOR_FORMAT_U8U8_RG = PSP2_GXM_COLOR_BASE_FORMAT_U8U8 | PSP2_GXM_COLOR_SWIZZLE2_RG,
	PSP2_GXM_COLOR_FORMAT_U8U8_RA = PSP2_GXM_COLOR_BASE_FORMAT_U8U8 | PSP2_GXM_COLOR_SWIZZLE2_RA,
	PSP2_GXM_COLOR_FORMAT_U8U8_AR = PSP2_GXM_COLOR_BASE_FORMAT_U8U8 | PSP2_GXM_COLOR_SWIZZLE2_AR,

	PSP2_GXM_COLOR_FORMAT_S8S8_GR = PSP2_GXM_COLOR_BASE_FORMAT_S8S8 | PSP2_GXM_COLOR_SWIZZLE2_GR,
	PSP2_GXM_COLOR_FORMAT_S8S8_RG = PSP2_GXM_COLOR_BASE_FORMAT_S8S8 | PSP2_GXM_COLOR_SWIZZLE2_RG,
	PSP2_GXM_COLOR_FORMAT_S8S8_RA = PSP2_GXM_COLOR_BASE_FORMAT_S8S8 | PSP2_GXM_COLOR_SWIZZLE2_RA,
	PSP2_GXM_COLOR_FORMAT_S8S8_AR = PSP2_GXM_COLOR_BASE_FORMAT_S8S8 | PSP2_GXM_COLOR_SWIZZLE2_AR,

	PSP2_GXM_COLOR_FORMAT_U8S8S8U8_ABGR = PSP2_GXM_COLOR_BASE_FORMAT_U8S8S8U8 | PSP2_GXM_COLOR_SWIZZLE4_ABGR,
	PSP2_GXM_COLOR_FORMAT_U8U8S8S8_ARGB = PSP2_GXM_COLOR_BASE_FORMAT_U8S8S8U8 | PSP2_GXM_COLOR_SWIZZLE4_ARGB,
	PSP2_GXM_COLOR_FORMAT_U8S8S8U8_RGBA = PSP2_GXM_COLOR_BASE_FORMAT_U8S8S8U8 | PSP2_GXM_COLOR_SWIZZLE4_RGBA,
	PSP2_GXM_COLOR_FORMAT_S8S8U8U8_BGRA = PSP2_GXM_COLOR_BASE_FORMAT_U8S8S8U8 | PSP2_GXM_COLOR_SWIZZLE4_BGRA,

	PSP2_GXM_COLOR_FORMAT_S8S8S8S8_ABGR = PSP2_GXM_COLOR_BASE_FORMAT_S8S8S8S8 | PSP2_GXM_COLOR_SWIZZLE4_ABGR,
	PSP2_GXM_COLOR_FORMAT_S8S8S8S8_ARGB = PSP2_GXM_COLOR_BASE_FORMAT_S8S8S8S8 | PSP2_GXM_COLOR_SWIZZLE4_ARGB,
	PSP2_GXM_COLOR_FORMAT_S8S8S8S8_RGBA = PSP2_GXM_COLOR_BASE_FORMAT_S8S8S8S8 | PSP2_GXM_COLOR_SWIZZLE4_RGBA,
	PSP2_GXM_COLOR_FORMAT_S8S8S8S8_BGRA = PSP2_GXM_COLOR_BASE_FORMAT_S8S8S8S8 | PSP2_GXM_COLOR_SWIZZLE4_BGRA,

	PSP2_GXM_COLOR_FORMAT_F16F16F16F16_ABGR = PSP2_GXM_COLOR_BASE_FORMAT_F16F16F16F16 | PSP2_GXM_COLOR_SWIZZLE4_ABGR,
	PSP2_GXM_COLOR_FORMAT_F16F16F16F16_ARGB = PSP2_GXM_COLOR_BASE_FORMAT_F16F16F16F16 | PSP2_GXM_COLOR_SWIZZLE4_ARGB,
	PSP2_GXM_COLOR_FORMAT_F16F16F16F16_RGBA = PSP2_GXM_COLOR_BASE_FORMAT_F16F16F16F16 | PSP2_GXM_COLOR_SWIZZLE4_RGBA,
	PSP2_GXM_COLOR_FORMAT_F16F16F16F16_BGRA = PSP2_GXM_COLOR_BASE_FORMAT_F16F16F16F16 | PSP2_GXM_COLOR_SWIZZLE4_BGRA,

	PSP2_GXM_COLOR_FORMAT_F32F32_GR = PSP2_GXM_COLOR_BASE_FORMAT_F32F32 | PSP2_GXM_COLOR_SWIZZLE2_GR,
	PSP2_GXM_COLOR_FORMAT_F32F32_RG = PSP2_GXM_COLOR_BASE_FORMAT_F32F32 | PSP2_GXM_COLOR_SWIZZLE2_RG,

	PSP2_GXM_COLOR_FORMAT_F10F11F11_BGR = PSP2_GXM_COLOR_BASE_FORMAT_F11F11F10 | PSP2_GXM_COLOR_SWIZZLE3_BGR,
	PSP2_GXM_COLOR_FORMAT_F11F11F10_RGB = PSP2_GXM_COLOR_BASE_FORMAT_F11F11F10 | PSP2_GXM_COLOR_SWIZZLE3_RGB,

	PSP2_GXM_COLOR_FORMAT_SE5M9M9M9_BGR = PSP2_GXM_COLOR_BASE_FORMAT_SE5M9M9M9 | PSP2_GXM_COLOR_SWIZZLE3_BGR,
	PSP2_GXM_COLOR_FORMAT_SE5M9M9M9_RGB = PSP2_GXM_COLOR_BASE_FORMAT_SE5M9M9M9 | PSP2_GXM_COLOR_SWIZZLE3_RGB,

	PSP2_GXM_COLOR_FORMAT_U2F10F10F10_ABGR = PSP2_GXM_COLOR_BASE_FORMAT_U2F10F10F10 | PSP2_GXM_COLOR_SWIZZLE4_ABGR,
	PSP2_GXM_COLOR_FORMAT_U2F10F10F10_ARGB = PSP2_GXM_COLOR_BASE_FORMAT_U2F10F10F10 | PSP2_GXM_COLOR_SWIZZLE4_ARGB,
	PSP2_GXM_COLOR_FORMAT_F10F10F10U2_RGBA = PSP2_GXM_COLOR_BASE_FORMAT_U2F10F10F10 | PSP2_GXM_COLOR_SWIZZLE4_RGBA,
	PSP2_GXM_COLOR_FORMAT_F10F10F10U2_BGRA = PSP2_GXM_COLOR_BASE_FORMAT_U2F10F10F10 | PSP2_GXM_COLOR_SWIZZLE4_BGRA,

	// Legacy formats

	PSP2_GXM_COLOR_FORMAT_A8B8G8R8 = PSP2_GXM_COLOR_FORMAT_U8U8U8U8_ABGR,
	PSP2_GXM_COLOR_FORMAT_A8R8G8B8 = PSP2_GXM_COLOR_FORMAT_U8U8U8U8_ARGB,
	PSP2_GXM_COLOR_FORMAT_R5G6B5   = PSP2_GXM_COLOR_FORMAT_U5U6U5_RGB,
	PSP2_GXM_COLOR_FORMAT_A1R5G5B5 = PSP2_GXM_COLOR_FORMAT_U1U5U5U5_ARGB,
	PSP2_GXM_COLOR_FORMAT_A4R4G4B4 = PSP2_GXM_COLOR_FORMAT_U4U4U4U4_ARGB,
	PSP2_GXM_COLOR_FORMAT_A8 = PSP2_GXM_COLOR_FORMAT_U8_A
} SceGxmColorFormat;

typedef enum SceGxmColorSurfaceType {
	PSP2_GXM_COLOR_SURFACE_LINEAR	= 0x00000000u,
	PSP2_GXM_COLOR_SURFACE_TILED	= 0x04000000u,
	PSP2_GXM_COLOR_SURFACE_SWIZZLED	= 0x08000000u
} SceGxmColorSurfaceType;

typedef enum SceGxmColorSurfaceGammaMode {
	PSP2_GXM_COLOR_SURFACE_GAMMA_NONE	= 0x00000000u,
	PSP2_GXM_COLOR_SURFACE_GAMMA_R	= 0x00001000u,
	PSP2_GXM_COLOR_SURFACE_GAMMA_GR	= 0x00003000u,
	PSP2_GXM_COLOR_SURFACE_GAMMA_BGR	= 0x00001000u
} SceGxmColorSurfaceGammaMode;

typedef enum SceGxmColorSurfaceDitherMode {
	PSP2_GXM_COLOR_SURFACE_DITHER_DISABLED	= 0x00000000u,
	PSP2_GXM_COLOR_SURFACE_DITHER_ENABLED	= 0x00000008u
} SceGxmColorSurfaceDitherMode;

typedef enum SceGxmDepthStencilSurfaceType {
	PSP2_GXM_DEPTH_STENCIL_SURFACE_LINEAR	= 0x00000000u,
	PSP2_GXM_DEPTH_STENCIL_SURFACE_TILED	= 0x00011000u
} SceGxmDepthStencilSurfaceType;

typedef enum SceGxmOutputRegisterFormat {
	PSP2_GXM_OUTPUT_REGISTER_FORMAT_DECLARED,
	PSP2_GXM_OUTPUT_REGISTER_FORMAT_UCHAR4,
	PSP2_GXM_OUTPUT_REGISTER_FORMAT_CHAR4,
	PSP2_GXM_OUTPUT_REGISTER_FORMAT_USHORT2,
	PSP2_GXM_OUTPUT_REGISTER_FORMAT_SHORT2,
	PSP2_GXM_OUTPUT_REGISTER_FORMAT_HALF4,
	PSP2_GXM_OUTPUT_REGISTER_FORMAT_HALF2,
	PSP2_GXM_OUTPUT_REGISTER_FORMAT_FLOAT2,
	PSP2_GXM_OUTPUT_REGISTER_FORMAT_FLOAT
} SceGxmOutputRegisterFormat;

typedef enum SceGxmMultisampleMode {
	PSP2_GXM_MULTISAMPLE_NONE,
	PSP2_GXM_MULTISAMPLE_2X,
	PSP2_GXM_MULTISAMPLE_4X
} SceGxmMultisampleMode;

typedef enum SceGxmTextureAlignmentMode {
	PSP2_GXM_TEXTURE_ALIGNMENT
} SceGxmTextureAlignmentMode;

typedef enum SceGxmTextureSwizzle4Mode {
	PSP2_GXM_TEXTURE_SWIZZLE4_ABGR	= 0x00000000u,
	PSP2_GXM_TEXTURE_SWIZZLE4_ARGB	= 0x00001000u,
	PSP2_GXM_TEXTURE_SWIZZLE4_RGBA	= 0x00002000u,
	PSP2_GXM_TEXTURE_SWIZZLE4_BGRA	= 0x00003000u,
	PSP2_GXM_TEXTURE_SWIZZLE4_1BGR	= 0x00004000u,
	PSP2_GXM_TEXTURE_SWIZZLE4_1RGB	= 0x00005000u,
	PSP2_GXM_TEXTURE_SWIZZLE4_RGB1	= 0x00006000u,
	PSP2_GXM_TEXTURE_SWIZZLE4_BGR1	= 0x00007000u
} SceGxmTextureSwizzle4Mode;

typedef enum SceGxmTextureSwizzle3Mode {
	PSP2_GXM_TEXTURE_SWIZZLE3_BGR	= 0x00000000u,
	PSP2_GXM_TEXTURE_SWIZZLE3_RGB	= 0x00001000u
} SceGxmTextureSwizzle3Mode;

typedef enum SceGxmTextureSwizzle2Mode {
	PSP2_GXM_TEXTURE_SWIZZLE2_GR	= 0x00000000u,
	PSP2_GXM_TEXTURE_SWIZZLE2_00GR	= 0x00001000u,
	PSP2_GXM_TEXTURE_SWIZZLE2_GRRR	= 0x00002000u,
	PSP2_GXM_TEXTURE_SWIZZLE2_RGGG	= 0x00003000u,
	PSP2_GXM_TEXTURE_SWIZZLE2_GRGR	= 0x00004000u,
	PSP2_GXM_TEXTURE_SWIZZLE2_00RG	= 0x00005000u
} SceGxmTextureSwizzle2Mode;

typedef enum SceGxmTextureSwizzle2ModeAlt {
	PSP2_GXM_TEXTURE_SWIZZLE2_SD	= 0x00000000u,
	PSP2_GXM_TEXTURE_SWIZZLE2_DS	= 0x00001000u
} SceGxmTextureSwizzle2ModeAlt;

typedef enum SceGxmTextureSwizzle1Mode {
	PSP2_GXM_TEXTURE_SWIZZLE1_R	= 0x00000000u,
	PSP2_GXM_TEXTURE_SWIZZLE1_000R	= 0x00001000u,
	PSP2_GXM_TEXTURE_SWIZZLE1_111R	= 0x00002000u,
	PSP2_GXM_TEXTURE_SWIZZLE1_RRRR	= 0x00003000u,
	PSP2_GXM_TEXTURE_SWIZZLE1_0RRR	= 0x00004000u,
	PSP2_GXM_TEXTURE_SWIZZLE1_1RRR	= 0x00005000u,
	PSP2_GXM_TEXTURE_SWIZZLE1_R000	= 0x00006000u,
	PSP2_GXM_TEXTURE_SWIZZLE1_R111	= 0x00007000u
} SceGxmTextureSwizzle1Mode;

typedef enum SceGxmTextureSwizzleYUV422Mode {
	PSP2_GXM_TEXTURE_SWIZZLE_YUYV_CSC0	= 0x00000000u,
	PSP2_GXM_TEXTURE_SWIZZLE_YVYU_CSC0	= 0x00001000u,
	PSP2_GXM_TEXTURE_SWIZZLE_UYVY_CSC0	= 0x00002000u,
	PSP2_GXM_TEXTURE_SWIZZLE_VYUY_CSC0	= 0x00003000u,
	PSP2_GXM_TEXTURE_SWIZZLE_YUYV_CSC1	= 0x00004000u,
	PSP2_GXM_TEXTURE_SWIZZLE_YVYU_CSC1	= 0x00005000u,
	PSP2_GXM_TEXTURE_SWIZZLE_UYVY_CSC1	= 0x00006000u,
	PSP2_GXM_TEXTURE_SWIZZLE_VYUY_CSC1	= 0x00007000u
} SceGxmTextureSwizzleYUV422Mode;

typedef enum SceGxmTextureSwizzleYUV420Mode {
	PSP2_GXM_TEXTURE_SWIZZLE_YUV_CSC0	= 0x00000000u,
	PSP2_GXM_TEXTURE_SWIZZLE_YVU_CSC0	= 0x00001000u,
	PSP2_GXM_TEXTURE_SWIZZLE_YUV_CSC1	= 0x00002000u,
	PSP2_GXM_TEXTURE_SWIZZLE_YVU_CSC1	= 0x00003000u
} SceGxmTextureSwizzleYUV420Mode;

typedef enum SceGxmTextureBaseFormat {
	PSP2_GXM_TEXTURE_BASE_FORMAT_U8	= 0x00000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_S8	= 0x01000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_U4U4U4U4	= 0x02000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_U8U3U3U2	= 0x03000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_U1U5U5U5	= 0x04000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_U5U6U5	= 0x05000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_S5S5U6	= 0x06000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8	= 0x07000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8	= 0x08000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_U16	= 0x09000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_S16	= 0x0a000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_F16	= 0x0b000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8U8U8	= 0x0c000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8S8S8	= 0x0d000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_U2U10U10U10	= 0x0e000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16	= 0x0f000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16	= 0x10000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16	= 0x11000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_F32	= 0x12000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_F32M	= 0x13000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_X8S8S8U8	= 0x14000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_X8U24	= 0x15000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_U32	= 0x17000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_S32	= 0x18000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_SE5M9M9M9	= 0x19000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_F11F11F10	= 0x1a000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16F16F16	= 0x1b000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16U16U16	= 0x1c000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16S16S16	= 0x1d000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_F32F32	= 0x1e000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_U32U32	= 0x1f000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_PVRT2BPP	= 0x80000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_PVRT4BPP	= 0x81000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_PVRTII2BPP	= 0x82000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_PVRTII4BPP	= 0x83000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_UBC1	= 0x85000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_UBC2	= 0x86000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_UBC3	= 0x87000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_YUV420P2	= 0x90000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_YUV420P3	= 0x91000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_YUV422	= 0x92000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_P4	= 0x94000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_P8	= 0x95000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8U8	= 0x98000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8S8	= 0x99000000,
	PSP2_GXM_TEXTURE_BASE_FORMAT_U2F10F10F10	= 0x9a000000
} SceGxmTextureBaseFormat;

typedef enum SceGxmTextureFormat {
	// Supported formats

	PSP2_GXM_TEXTURE_FORMAT_U8_000R = PSP2_GXM_TEXTURE_BASE_FORMAT_U8 | PSP2_GXM_TEXTURE_SWIZZLE1_000R,
	PSP2_GXM_TEXTURE_FORMAT_U8_111R = PSP2_GXM_TEXTURE_BASE_FORMAT_U8 | PSP2_GXM_TEXTURE_SWIZZLE1_111R,
	PSP2_GXM_TEXTURE_FORMAT_U8_RRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_U8 | PSP2_GXM_TEXTURE_SWIZZLE1_RRRR,
	PSP2_GXM_TEXTURE_FORMAT_U8_0RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_U8 | PSP2_GXM_TEXTURE_SWIZZLE1_0RRR,
	PSP2_GXM_TEXTURE_FORMAT_U8_1RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_U8 | PSP2_GXM_TEXTURE_SWIZZLE1_1RRR,
	PSP2_GXM_TEXTURE_FORMAT_U8_R000 = PSP2_GXM_TEXTURE_BASE_FORMAT_U8 | PSP2_GXM_TEXTURE_SWIZZLE1_R000,
	PSP2_GXM_TEXTURE_FORMAT_U8_R111 = PSP2_GXM_TEXTURE_BASE_FORMAT_U8 | PSP2_GXM_TEXTURE_SWIZZLE1_R111,
	PSP2_GXM_TEXTURE_FORMAT_U8_R = PSP2_GXM_TEXTURE_BASE_FORMAT_U8 | PSP2_GXM_TEXTURE_SWIZZLE1_R,

	PSP2_GXM_TEXTURE_FORMAT_S8_000R = PSP2_GXM_TEXTURE_BASE_FORMAT_S8 | PSP2_GXM_TEXTURE_SWIZZLE1_000R,
	PSP2_GXM_TEXTURE_FORMAT_S8_111R = PSP2_GXM_TEXTURE_BASE_FORMAT_S8 | PSP2_GXM_TEXTURE_SWIZZLE1_111R,
	PSP2_GXM_TEXTURE_FORMAT_S8_RRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_S8 | PSP2_GXM_TEXTURE_SWIZZLE1_RRRR,
	PSP2_GXM_TEXTURE_FORMAT_S8_0RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_S8 | PSP2_GXM_TEXTURE_SWIZZLE1_0RRR,
	PSP2_GXM_TEXTURE_FORMAT_S8_1RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_S8 | PSP2_GXM_TEXTURE_SWIZZLE1_1RRR,
	PSP2_GXM_TEXTURE_FORMAT_S8_R000 = PSP2_GXM_TEXTURE_BASE_FORMAT_S8 | PSP2_GXM_TEXTURE_SWIZZLE1_R000,
	PSP2_GXM_TEXTURE_FORMAT_S8_R111 = PSP2_GXM_TEXTURE_BASE_FORMAT_S8 | PSP2_GXM_TEXTURE_SWIZZLE1_R111,
	PSP2_GXM_TEXTURE_FORMAT_S8_R = PSP2_GXM_TEXTURE_BASE_FORMAT_S8 | PSP2_GXM_TEXTURE_SWIZZLE1_R,

	PSP2_GXM_TEXTURE_FORMAT_U4U4U4U4_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U4U4U4U4 | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_U4U4U4U4_ARGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U4U4U4U4 | PSP2_GXM_TEXTURE_SWIZZLE4_ARGB,
	PSP2_GXM_TEXTURE_FORMAT_U4U4U4U4_RGBA = PSP2_GXM_TEXTURE_BASE_FORMAT_U4U4U4U4 | PSP2_GXM_TEXTURE_SWIZZLE4_RGBA,
	PSP2_GXM_TEXTURE_FORMAT_U4U4U4U4_BGRA = PSP2_GXM_TEXTURE_BASE_FORMAT_U4U4U4U4 | PSP2_GXM_TEXTURE_SWIZZLE4_BGRA,
	PSP2_GXM_TEXTURE_FORMAT_X4U4U4U4_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U4U4U4U4 | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,
	PSP2_GXM_TEXTURE_FORMAT_X4U4U4U4_1RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U4U4U4U4 | PSP2_GXM_TEXTURE_SWIZZLE4_1RGB,
	PSP2_GXM_TEXTURE_FORMAT_U4U4U4X4_RGB1 = PSP2_GXM_TEXTURE_BASE_FORMAT_U4U4U4U4 | PSP2_GXM_TEXTURE_SWIZZLE4_RGB1,
	PSP2_GXM_TEXTURE_FORMAT_U4U4U4X4_BGR1 = PSP2_GXM_TEXTURE_BASE_FORMAT_U4U4U4U4 | PSP2_GXM_TEXTURE_SWIZZLE4_BGR1,

	PSP2_GXM_TEXTURE_FORMAT_U8U3U3U2_ARGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U3U3U2,

	PSP2_GXM_TEXTURE_FORMAT_U1U5U5U5_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U1U5U5U5 | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_U1U5U5U5_ARGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U1U5U5U5 | PSP2_GXM_TEXTURE_SWIZZLE4_ARGB,
	PSP2_GXM_TEXTURE_FORMAT_U5U5U5U1_RGBA = PSP2_GXM_TEXTURE_BASE_FORMAT_U1U5U5U5 | PSP2_GXM_TEXTURE_SWIZZLE4_RGBA,
	PSP2_GXM_TEXTURE_FORMAT_U5U5U5U1_BGRA = PSP2_GXM_TEXTURE_BASE_FORMAT_U1U5U5U5 | PSP2_GXM_TEXTURE_SWIZZLE4_BGRA,
	PSP2_GXM_TEXTURE_FORMAT_X1U5U5U5_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U1U5U5U5 | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,
	PSP2_GXM_TEXTURE_FORMAT_X1U5U5U5_1RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U1U5U5U5 | PSP2_GXM_TEXTURE_SWIZZLE4_1RGB,
	PSP2_GXM_TEXTURE_FORMAT_U5U5U5X1_RGB1 = PSP2_GXM_TEXTURE_BASE_FORMAT_U1U5U5U5 | PSP2_GXM_TEXTURE_SWIZZLE4_RGB1,
	PSP2_GXM_TEXTURE_FORMAT_U5U5U5X1_BGR1 = PSP2_GXM_TEXTURE_BASE_FORMAT_U1U5U5U5 | PSP2_GXM_TEXTURE_SWIZZLE4_BGR1,

	PSP2_GXM_TEXTURE_FORMAT_U5U6U5_BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U5U6U5 | PSP2_GXM_TEXTURE_SWIZZLE3_BGR,
	PSP2_GXM_TEXTURE_FORMAT_U5U6U5_RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U5U6U5 | PSP2_GXM_TEXTURE_SWIZZLE3_RGB,

	PSP2_GXM_TEXTURE_FORMAT_U6S5S5_BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_S5S5U6 | PSP2_GXM_TEXTURE_SWIZZLE3_BGR,
	PSP2_GXM_TEXTURE_FORMAT_S5S5U6_RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_S5S5U6 | PSP2_GXM_TEXTURE_SWIZZLE3_RGB,

	PSP2_GXM_TEXTURE_FORMAT_U8U8_00GR = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8 | PSP2_GXM_TEXTURE_SWIZZLE2_00GR,
	PSP2_GXM_TEXTURE_FORMAT_U8U8_GRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8 | PSP2_GXM_TEXTURE_SWIZZLE2_GRRR,
	PSP2_GXM_TEXTURE_FORMAT_U8U8_RGGG = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8 | PSP2_GXM_TEXTURE_SWIZZLE2_RGGG,
	PSP2_GXM_TEXTURE_FORMAT_U8U8_GRGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8 | PSP2_GXM_TEXTURE_SWIZZLE2_GRGR,
	PSP2_GXM_TEXTURE_FORMAT_U8U8_00RG = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8 | PSP2_GXM_TEXTURE_SWIZZLE2_00RG,
	PSP2_GXM_TEXTURE_FORMAT_U8U8_GR = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8 | PSP2_GXM_TEXTURE_SWIZZLE2_GR,

	PSP2_GXM_TEXTURE_FORMAT_S8S8_00GR = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8 | PSP2_GXM_TEXTURE_SWIZZLE2_00GR,
	PSP2_GXM_TEXTURE_FORMAT_S8S8_GRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8 | PSP2_GXM_TEXTURE_SWIZZLE2_GRRR,
	PSP2_GXM_TEXTURE_FORMAT_S8S8_RGGG = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8 | PSP2_GXM_TEXTURE_SWIZZLE2_RGGG,
	PSP2_GXM_TEXTURE_FORMAT_S8S8_GRGR = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8 | PSP2_GXM_TEXTURE_SWIZZLE2_GRGR,
	PSP2_GXM_TEXTURE_FORMAT_S8S8_00RG = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8 | PSP2_GXM_TEXTURE_SWIZZLE2_00RG,
	PSP2_GXM_TEXTURE_FORMAT_S8S8_GR = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8 | PSP2_GXM_TEXTURE_SWIZZLE2_GR,

	PSP2_GXM_TEXTURE_FORMAT_U16_000R = PSP2_GXM_TEXTURE_BASE_FORMAT_U16 | PSP2_GXM_TEXTURE_SWIZZLE1_000R,
	PSP2_GXM_TEXTURE_FORMAT_U16_111R = PSP2_GXM_TEXTURE_BASE_FORMAT_U16 | PSP2_GXM_TEXTURE_SWIZZLE1_111R,
	PSP2_GXM_TEXTURE_FORMAT_U16_RRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_U16 | PSP2_GXM_TEXTURE_SWIZZLE1_RRRR,
	PSP2_GXM_TEXTURE_FORMAT_U16_0RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_U16 | PSP2_GXM_TEXTURE_SWIZZLE1_0RRR,
	PSP2_GXM_TEXTURE_FORMAT_U16_1RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_U16 | PSP2_GXM_TEXTURE_SWIZZLE1_1RRR,
	PSP2_GXM_TEXTURE_FORMAT_U16_R000 = PSP2_GXM_TEXTURE_BASE_FORMAT_U16 | PSP2_GXM_TEXTURE_SWIZZLE1_R000,
	PSP2_GXM_TEXTURE_FORMAT_U16_R111 = PSP2_GXM_TEXTURE_BASE_FORMAT_U16 | PSP2_GXM_TEXTURE_SWIZZLE1_R111,
	PSP2_GXM_TEXTURE_FORMAT_U16_R = PSP2_GXM_TEXTURE_BASE_FORMAT_U16 | PSP2_GXM_TEXTURE_SWIZZLE1_R,

	PSP2_GXM_TEXTURE_FORMAT_S16_000R = PSP2_GXM_TEXTURE_BASE_FORMAT_S16 | PSP2_GXM_TEXTURE_SWIZZLE1_000R,
	PSP2_GXM_TEXTURE_FORMAT_S16_111R = PSP2_GXM_TEXTURE_BASE_FORMAT_S16 | PSP2_GXM_TEXTURE_SWIZZLE1_111R,
	PSP2_GXM_TEXTURE_FORMAT_S16_RRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_S16 | PSP2_GXM_TEXTURE_SWIZZLE1_RRRR,
	PSP2_GXM_TEXTURE_FORMAT_S16_0RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_S16 | PSP2_GXM_TEXTURE_SWIZZLE1_0RRR,
	PSP2_GXM_TEXTURE_FORMAT_S16_1RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_S16 | PSP2_GXM_TEXTURE_SWIZZLE1_1RRR,
	PSP2_GXM_TEXTURE_FORMAT_S16_R000 = PSP2_GXM_TEXTURE_BASE_FORMAT_S16 | PSP2_GXM_TEXTURE_SWIZZLE1_R000,
	PSP2_GXM_TEXTURE_FORMAT_S16_R111 = PSP2_GXM_TEXTURE_BASE_FORMAT_S16 | PSP2_GXM_TEXTURE_SWIZZLE1_R111,
	PSP2_GXM_TEXTURE_FORMAT_S16_R = PSP2_GXM_TEXTURE_BASE_FORMAT_S16 | PSP2_GXM_TEXTURE_SWIZZLE1_R,

	PSP2_GXM_TEXTURE_FORMAT_F16_000R = PSP2_GXM_TEXTURE_BASE_FORMAT_F16 | PSP2_GXM_TEXTURE_SWIZZLE1_000R,
	PSP2_GXM_TEXTURE_FORMAT_F16_111R = PSP2_GXM_TEXTURE_BASE_FORMAT_F16 | PSP2_GXM_TEXTURE_SWIZZLE1_111R,
	PSP2_GXM_TEXTURE_FORMAT_F16_RRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_F16 | PSP2_GXM_TEXTURE_SWIZZLE1_RRRR,
	PSP2_GXM_TEXTURE_FORMAT_F16_0RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_F16 | PSP2_GXM_TEXTURE_SWIZZLE1_0RRR,
	PSP2_GXM_TEXTURE_FORMAT_F16_1RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_F16 | PSP2_GXM_TEXTURE_SWIZZLE1_1RRR,
	PSP2_GXM_TEXTURE_FORMAT_F16_R000 = PSP2_GXM_TEXTURE_BASE_FORMAT_F16 | PSP2_GXM_TEXTURE_SWIZZLE1_R000,
	PSP2_GXM_TEXTURE_FORMAT_F16_R111 = PSP2_GXM_TEXTURE_BASE_FORMAT_F16 | PSP2_GXM_TEXTURE_SWIZZLE1_R111,
	PSP2_GXM_TEXTURE_FORMAT_F16_R = PSP2_GXM_TEXTURE_BASE_FORMAT_F16 | PSP2_GXM_TEXTURE_SWIZZLE1_R,

	PSP2_GXM_TEXTURE_FORMAT_U8U8U8U8_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8U8U8 | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_U8U8U8U8_ARGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8U8U8 | PSP2_GXM_TEXTURE_SWIZZLE4_ARGB,
	PSP2_GXM_TEXTURE_FORMAT_U8U8U8U8_RGBA = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8U8U8 | PSP2_GXM_TEXTURE_SWIZZLE4_RGBA,
	PSP2_GXM_TEXTURE_FORMAT_U8U8U8U8_BGRA = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8U8U8 | PSP2_GXM_TEXTURE_SWIZZLE4_BGRA,
	PSP2_GXM_TEXTURE_FORMAT_X8U8U8U8_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8U8U8 | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,
	PSP2_GXM_TEXTURE_FORMAT_X8U8U8U8_1RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8U8U8 | PSP2_GXM_TEXTURE_SWIZZLE4_1RGB,
	PSP2_GXM_TEXTURE_FORMAT_U8U8U8X8_RGB1 = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8U8U8 | PSP2_GXM_TEXTURE_SWIZZLE4_RGB1,
	PSP2_GXM_TEXTURE_FORMAT_U8U8U8X8_BGR1 = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8U8U8 | PSP2_GXM_TEXTURE_SWIZZLE4_BGR1,

	PSP2_GXM_TEXTURE_FORMAT_S8S8S8S8_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8S8S8 | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_S8S8S8S8_ARGB = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8S8S8 | PSP2_GXM_TEXTURE_SWIZZLE4_ARGB,
	PSP2_GXM_TEXTURE_FORMAT_S8S8S8S8_RGBA = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8S8S8 | PSP2_GXM_TEXTURE_SWIZZLE4_RGBA,
	PSP2_GXM_TEXTURE_FORMAT_S8S8S8S8_BGRA = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8S8S8 | PSP2_GXM_TEXTURE_SWIZZLE4_BGRA,
	PSP2_GXM_TEXTURE_FORMAT_X8S8S8S8_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8S8S8 | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,
	PSP2_GXM_TEXTURE_FORMAT_X8S8S8S8_1RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8S8S8 | PSP2_GXM_TEXTURE_SWIZZLE4_1RGB,
	PSP2_GXM_TEXTURE_FORMAT_S8S8S8X8_RGB1 = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8S8S8 | PSP2_GXM_TEXTURE_SWIZZLE4_RGB1,
	PSP2_GXM_TEXTURE_FORMAT_S8S8S8X8_BGR1 = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8S8S8 | PSP2_GXM_TEXTURE_SWIZZLE4_BGR1,

	PSP2_GXM_TEXTURE_FORMAT_U2U10U10U10_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U2U10U10U10 | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_U2U10U10U10_ARGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U2U10U10U10 | PSP2_GXM_TEXTURE_SWIZZLE4_ARGB,
	PSP2_GXM_TEXTURE_FORMAT_U10U10U10U2_RGBA = PSP2_GXM_TEXTURE_BASE_FORMAT_U2U10U10U10 | PSP2_GXM_TEXTURE_SWIZZLE4_RGBA,
	PSP2_GXM_TEXTURE_FORMAT_U10U10U10U2_BGRA = PSP2_GXM_TEXTURE_BASE_FORMAT_U2U10U10U10 | PSP2_GXM_TEXTURE_SWIZZLE4_BGRA,
	PSP2_GXM_TEXTURE_FORMAT_X2U10U10U10_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U2U10U10U10 | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,
	PSP2_GXM_TEXTURE_FORMAT_X2U10U10U10_1RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U2U10U10U10 | PSP2_GXM_TEXTURE_SWIZZLE4_1RGB,
	PSP2_GXM_TEXTURE_FORMAT_U10U10U10X2_RGB1 = PSP2_GXM_TEXTURE_BASE_FORMAT_U2U10U10U10 | PSP2_GXM_TEXTURE_SWIZZLE4_RGB1,
	PSP2_GXM_TEXTURE_FORMAT_U10U10U10X2_BGR1 = PSP2_GXM_TEXTURE_BASE_FORMAT_U2U10U10U10 | PSP2_GXM_TEXTURE_SWIZZLE4_BGR1,

	PSP2_GXM_TEXTURE_FORMAT_U16U16_00GR = PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16 | PSP2_GXM_TEXTURE_SWIZZLE2_00GR,
	PSP2_GXM_TEXTURE_FORMAT_U16U16_GRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16 | PSP2_GXM_TEXTURE_SWIZZLE2_GRRR,
	PSP2_GXM_TEXTURE_FORMAT_U16U16_RGGG = PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16 | PSP2_GXM_TEXTURE_SWIZZLE2_RGGG,
	PSP2_GXM_TEXTURE_FORMAT_U16U16_GRGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16 | PSP2_GXM_TEXTURE_SWIZZLE2_GRGR,
	PSP2_GXM_TEXTURE_FORMAT_U16U16_00RG = PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16 | PSP2_GXM_TEXTURE_SWIZZLE2_00RG,
	PSP2_GXM_TEXTURE_FORMAT_U16U16_GR = PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16 | PSP2_GXM_TEXTURE_SWIZZLE2_GR,

	PSP2_GXM_TEXTURE_FORMAT_S16S16_00GR = PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16 | PSP2_GXM_TEXTURE_SWIZZLE2_00GR,
	PSP2_GXM_TEXTURE_FORMAT_S16S16_GRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16 | PSP2_GXM_TEXTURE_SWIZZLE2_GRRR,
	PSP2_GXM_TEXTURE_FORMAT_S16S16_RGGG = PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16 | PSP2_GXM_TEXTURE_SWIZZLE2_RGGG,
	PSP2_GXM_TEXTURE_FORMAT_S16S16_GRGR = PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16 | PSP2_GXM_TEXTURE_SWIZZLE2_GRGR,
	PSP2_GXM_TEXTURE_FORMAT_S16S16_00RG = PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16 | PSP2_GXM_TEXTURE_SWIZZLE2_00RG,
	PSP2_GXM_TEXTURE_FORMAT_S16S16_GR = PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16 | PSP2_GXM_TEXTURE_SWIZZLE2_GR,

	PSP2_GXM_TEXTURE_FORMAT_F16F16_00GR = PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16 | PSP2_GXM_TEXTURE_SWIZZLE2_00GR,
	PSP2_GXM_TEXTURE_FORMAT_F16F16_GRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16 | PSP2_GXM_TEXTURE_SWIZZLE2_GRRR,
	PSP2_GXM_TEXTURE_FORMAT_F16F16_RGGG = PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16 | PSP2_GXM_TEXTURE_SWIZZLE2_RGGG,
	PSP2_GXM_TEXTURE_FORMAT_F16F16_GRGR = PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16 | PSP2_GXM_TEXTURE_SWIZZLE2_GRGR,
	PSP2_GXM_TEXTURE_FORMAT_F16F16_00RG = PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16 | PSP2_GXM_TEXTURE_SWIZZLE2_00RG,
	PSP2_GXM_TEXTURE_FORMAT_F16F16_GR = PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16 | PSP2_GXM_TEXTURE_SWIZZLE2_GR,

	PSP2_GXM_TEXTURE_FORMAT_F32_000R = PSP2_GXM_TEXTURE_BASE_FORMAT_F32 | PSP2_GXM_TEXTURE_SWIZZLE1_000R,
	PSP2_GXM_TEXTURE_FORMAT_F32_111R = PSP2_GXM_TEXTURE_BASE_FORMAT_F32 | PSP2_GXM_TEXTURE_SWIZZLE1_111R,
	PSP2_GXM_TEXTURE_FORMAT_F32_RRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_F32 | PSP2_GXM_TEXTURE_SWIZZLE1_RRRR,
	PSP2_GXM_TEXTURE_FORMAT_F32_0RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_F32 | PSP2_GXM_TEXTURE_SWIZZLE1_0RRR,
	PSP2_GXM_TEXTURE_FORMAT_F32_1RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_F32 | PSP2_GXM_TEXTURE_SWIZZLE1_1RRR,
	PSP2_GXM_TEXTURE_FORMAT_F32_R000 = PSP2_GXM_TEXTURE_BASE_FORMAT_F32 | PSP2_GXM_TEXTURE_SWIZZLE1_R000,
	PSP2_GXM_TEXTURE_FORMAT_F32_R111 = PSP2_GXM_TEXTURE_BASE_FORMAT_F32 | PSP2_GXM_TEXTURE_SWIZZLE1_R111,
	PSP2_GXM_TEXTURE_FORMAT_F32_R = PSP2_GXM_TEXTURE_BASE_FORMAT_F32 | PSP2_GXM_TEXTURE_SWIZZLE1_R,

	PSP2_GXM_TEXTURE_FORMAT_F32M_000R = PSP2_GXM_TEXTURE_BASE_FORMAT_F32M | PSP2_GXM_TEXTURE_SWIZZLE1_000R,
	PSP2_GXM_TEXTURE_FORMAT_F32M_111R = PSP2_GXM_TEXTURE_BASE_FORMAT_F32M | PSP2_GXM_TEXTURE_SWIZZLE1_111R,
	PSP2_GXM_TEXTURE_FORMAT_F32M_RRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_F32M | PSP2_GXM_TEXTURE_SWIZZLE1_RRRR,
	PSP2_GXM_TEXTURE_FORMAT_F32M_0RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_F32M | PSP2_GXM_TEXTURE_SWIZZLE1_0RRR,
	PSP2_GXM_TEXTURE_FORMAT_F32M_1RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_F32M | PSP2_GXM_TEXTURE_SWIZZLE1_1RRR,
	PSP2_GXM_TEXTURE_FORMAT_F32M_R000 = PSP2_GXM_TEXTURE_BASE_FORMAT_F32M | PSP2_GXM_TEXTURE_SWIZZLE1_R000,
	PSP2_GXM_TEXTURE_FORMAT_F32M_R111 = PSP2_GXM_TEXTURE_BASE_FORMAT_F32M | PSP2_GXM_TEXTURE_SWIZZLE1_R111,
	PSP2_GXM_TEXTURE_FORMAT_F32M_R = PSP2_GXM_TEXTURE_BASE_FORMAT_F32M | PSP2_GXM_TEXTURE_SWIZZLE1_R,

	PSP2_GXM_TEXTURE_FORMAT_X8S8S8U8_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_X8S8S8U8 | PSP2_GXM_TEXTURE_SWIZZLE3_BGR,
	PSP2_GXM_TEXTURE_FORMAT_X8U8S8S8_1RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_X8S8S8U8 | PSP2_GXM_TEXTURE_SWIZZLE3_RGB,

	PSP2_GXM_TEXTURE_FORMAT_X8U24_SD = PSP2_GXM_TEXTURE_BASE_FORMAT_X8U24 | PSP2_GXM_TEXTURE_SWIZZLE2_SD,
	PSP2_GXM_TEXTURE_FORMAT_U24X8_DS = PSP2_GXM_TEXTURE_BASE_FORMAT_X8U24 | PSP2_GXM_TEXTURE_SWIZZLE2_DS,

	PSP2_GXM_TEXTURE_FORMAT_U32_000R = PSP2_GXM_TEXTURE_BASE_FORMAT_U32 | PSP2_GXM_TEXTURE_SWIZZLE1_000R,
	PSP2_GXM_TEXTURE_FORMAT_U32_111R = PSP2_GXM_TEXTURE_BASE_FORMAT_U32 | PSP2_GXM_TEXTURE_SWIZZLE1_111R,
	PSP2_GXM_TEXTURE_FORMAT_U32_RRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_U32 | PSP2_GXM_TEXTURE_SWIZZLE1_RRRR,
	PSP2_GXM_TEXTURE_FORMAT_U32_0RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_U32 | PSP2_GXM_TEXTURE_SWIZZLE1_0RRR,
	PSP2_GXM_TEXTURE_FORMAT_U32_1RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_U32 | PSP2_GXM_TEXTURE_SWIZZLE1_1RRR,
	PSP2_GXM_TEXTURE_FORMAT_U32_R000 = PSP2_GXM_TEXTURE_BASE_FORMAT_U32 | PSP2_GXM_TEXTURE_SWIZZLE1_R000,
	PSP2_GXM_TEXTURE_FORMAT_U32_R111 = PSP2_GXM_TEXTURE_BASE_FORMAT_U32 | PSP2_GXM_TEXTURE_SWIZZLE1_R111,
	PSP2_GXM_TEXTURE_FORMAT_U32_R = PSP2_GXM_TEXTURE_BASE_FORMAT_U32 | PSP2_GXM_TEXTURE_SWIZZLE1_R,

	PSP2_GXM_TEXTURE_FORMAT_S32_000R = PSP2_GXM_TEXTURE_BASE_FORMAT_S32 | PSP2_GXM_TEXTURE_SWIZZLE1_000R,
	PSP2_GXM_TEXTURE_FORMAT_S32_111R = PSP2_GXM_TEXTURE_BASE_FORMAT_S32 | PSP2_GXM_TEXTURE_SWIZZLE1_111R,
	PSP2_GXM_TEXTURE_FORMAT_S32_RRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_S32 | PSP2_GXM_TEXTURE_SWIZZLE1_RRRR,
	PSP2_GXM_TEXTURE_FORMAT_S32_0RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_S32 | PSP2_GXM_TEXTURE_SWIZZLE1_0RRR,
	PSP2_GXM_TEXTURE_FORMAT_S32_1RRR = PSP2_GXM_TEXTURE_BASE_FORMAT_S32 | PSP2_GXM_TEXTURE_SWIZZLE1_1RRR,
	PSP2_GXM_TEXTURE_FORMAT_S32_R000 = PSP2_GXM_TEXTURE_BASE_FORMAT_S32 | PSP2_GXM_TEXTURE_SWIZZLE1_R000,
	PSP2_GXM_TEXTURE_FORMAT_S32_R111 = PSP2_GXM_TEXTURE_BASE_FORMAT_S32 | PSP2_GXM_TEXTURE_SWIZZLE1_R111,
	PSP2_GXM_TEXTURE_FORMAT_S32_R = PSP2_GXM_TEXTURE_BASE_FORMAT_S32 | PSP2_GXM_TEXTURE_SWIZZLE1_R,

	PSP2_GXM_TEXTURE_FORMAT_SE5M9M9M9_BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_SE5M9M9M9 | PSP2_GXM_TEXTURE_SWIZZLE3_BGR,
	PSP2_GXM_TEXTURE_FORMAT_SE5M9M9M9_RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_SE5M9M9M9 | PSP2_GXM_TEXTURE_SWIZZLE3_RGB,

	PSP2_GXM_TEXTURE_FORMAT_F10F11F11_BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_F11F11F10 | PSP2_GXM_TEXTURE_SWIZZLE3_BGR,
	PSP2_GXM_TEXTURE_FORMAT_F11F11F10_RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_F11F11F10 | PSP2_GXM_TEXTURE_SWIZZLE3_RGB,

	PSP2_GXM_TEXTURE_FORMAT_F16F16F16F16_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16F16F16 | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_F16F16F16F16_ARGB = PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16F16F16 | PSP2_GXM_TEXTURE_SWIZZLE4_ARGB,
	PSP2_GXM_TEXTURE_FORMAT_F16F16F16F16_RGBA = PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16F16F16 | PSP2_GXM_TEXTURE_SWIZZLE4_RGBA,
	PSP2_GXM_TEXTURE_FORMAT_F16F16F16F16_BGRA = PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16F16F16 | PSP2_GXM_TEXTURE_SWIZZLE4_BGRA,
	PSP2_GXM_TEXTURE_FORMAT_X16F16F16F16_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16F16F16 | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,
	PSP2_GXM_TEXTURE_FORMAT_X16F16F16F16_1RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16F16F16 | PSP2_GXM_TEXTURE_SWIZZLE4_1RGB,
	PSP2_GXM_TEXTURE_FORMAT_F16F16F16X16_RGB1 = PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16F16F16 | PSP2_GXM_TEXTURE_SWIZZLE4_RGB1,
	PSP2_GXM_TEXTURE_FORMAT_F16F16F16X16_BGR1 = PSP2_GXM_TEXTURE_BASE_FORMAT_F16F16F16F16 | PSP2_GXM_TEXTURE_SWIZZLE4_BGR1,

	PSP2_GXM_TEXTURE_FORMAT_U16U16U16U16_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16U16U16 | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_U16U16U16U16_ARGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16U16U16 | PSP2_GXM_TEXTURE_SWIZZLE4_ARGB,
	PSP2_GXM_TEXTURE_FORMAT_U16U16U16U16_RGBA = PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16U16U16 | PSP2_GXM_TEXTURE_SWIZZLE4_RGBA,
	PSP2_GXM_TEXTURE_FORMAT_U16U16U16U16_BGRA = PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16U16U16 | PSP2_GXM_TEXTURE_SWIZZLE4_BGRA,
	PSP2_GXM_TEXTURE_FORMAT_X16U16U16U16_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16U16U16 | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,
	PSP2_GXM_TEXTURE_FORMAT_X16U16U16U16_1RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16U16U16 | PSP2_GXM_TEXTURE_SWIZZLE4_1RGB,
	PSP2_GXM_TEXTURE_FORMAT_U16U16U16X16_RGB1 = PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16U16U16 | PSP2_GXM_TEXTURE_SWIZZLE4_RGB1,
	PSP2_GXM_TEXTURE_FORMAT_U16U16U16X16_BGR1 = PSP2_GXM_TEXTURE_BASE_FORMAT_U16U16U16U16 | PSP2_GXM_TEXTURE_SWIZZLE4_BGR1,

	PSP2_GXM_TEXTURE_FORMAT_S16S16S16S16_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16S16S16 | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_S16S16S16S16_ARGB = PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16S16S16 | PSP2_GXM_TEXTURE_SWIZZLE4_ARGB,
	PSP2_GXM_TEXTURE_FORMAT_S16S16S16S16_RGBA = PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16S16S16 | PSP2_GXM_TEXTURE_SWIZZLE4_RGBA,
	PSP2_GXM_TEXTURE_FORMAT_S16S16S16S16_BGRA = PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16S16S16 | PSP2_GXM_TEXTURE_SWIZZLE4_BGRA,
	PSP2_GXM_TEXTURE_FORMAT_X16S16S16S16_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16S16S16 | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,
	PSP2_GXM_TEXTURE_FORMAT_X16S16S16S16_1RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16S16S16 | PSP2_GXM_TEXTURE_SWIZZLE4_1RGB,
	PSP2_GXM_TEXTURE_FORMAT_S16S16S16X16_RGB1 = PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16S16S16 | PSP2_GXM_TEXTURE_SWIZZLE4_RGB1,
	PSP2_GXM_TEXTURE_FORMAT_S16S16S16X16_BGR1 = PSP2_GXM_TEXTURE_BASE_FORMAT_S16S16S16S16 | PSP2_GXM_TEXTURE_SWIZZLE4_BGR1,

	PSP2_GXM_TEXTURE_FORMAT_F32F32_00GR = PSP2_GXM_TEXTURE_BASE_FORMAT_F32F32 | PSP2_GXM_TEXTURE_SWIZZLE2_00GR,
	PSP2_GXM_TEXTURE_FORMAT_F32F32_GRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_F32F32 | PSP2_GXM_TEXTURE_SWIZZLE2_GRRR,
	PSP2_GXM_TEXTURE_FORMAT_F32F32_RGGG = PSP2_GXM_TEXTURE_BASE_FORMAT_F32F32 | PSP2_GXM_TEXTURE_SWIZZLE2_RGGG,
	PSP2_GXM_TEXTURE_FORMAT_F32F32_GRGR = PSP2_GXM_TEXTURE_BASE_FORMAT_F32F32 | PSP2_GXM_TEXTURE_SWIZZLE2_GRGR,
	PSP2_GXM_TEXTURE_FORMAT_F32F32_00RG = PSP2_GXM_TEXTURE_BASE_FORMAT_F32F32 | PSP2_GXM_TEXTURE_SWIZZLE2_00RG,
	PSP2_GXM_TEXTURE_FORMAT_F32F32_GR = PSP2_GXM_TEXTURE_BASE_FORMAT_F32F32 | PSP2_GXM_TEXTURE_SWIZZLE2_GR,

	PSP2_GXM_TEXTURE_FORMAT_U32U32_00GR = PSP2_GXM_TEXTURE_BASE_FORMAT_U32U32 | PSP2_GXM_TEXTURE_SWIZZLE2_00GR,
	PSP2_GXM_TEXTURE_FORMAT_U32U32_GRRR = PSP2_GXM_TEXTURE_BASE_FORMAT_U32U32 | PSP2_GXM_TEXTURE_SWIZZLE2_GRRR,
	PSP2_GXM_TEXTURE_FORMAT_U32U32_RGGG = PSP2_GXM_TEXTURE_BASE_FORMAT_U32U32 | PSP2_GXM_TEXTURE_SWIZZLE2_RGGG,
	PSP2_GXM_TEXTURE_FORMAT_U32U32_GRGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U32U32 | PSP2_GXM_TEXTURE_SWIZZLE2_GRGR,
	PSP2_GXM_TEXTURE_FORMAT_U32U32_00RG = PSP2_GXM_TEXTURE_BASE_FORMAT_U32U32 | PSP2_GXM_TEXTURE_SWIZZLE2_00RG,
	PSP2_GXM_TEXTURE_FORMAT_U32U32_GR = PSP2_GXM_TEXTURE_BASE_FORMAT_U32U32 | PSP2_GXM_TEXTURE_SWIZZLE2_GR,

	PSP2_GXM_TEXTURE_FORMAT_PVRT2BPP_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_PVRT2BPP | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_PVRT2BPP_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_PVRT2BPP | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,

	PSP2_GXM_TEXTURE_FORMAT_PVRT4BPP_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_PVRT4BPP | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_PVRT4BPP_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_PVRT4BPP | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,

	PSP2_GXM_TEXTURE_FORMAT_PVRTII2BPP_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_PVRTII2BPP | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_PVRTII2BPP_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_PVRTII2BPP | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,

	PSP2_GXM_TEXTURE_FORMAT_PVRTII4BPP_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_PVRTII4BPP | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_PVRTII4BPP_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_PVRTII4BPP | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,

	PSP2_GXM_TEXTURE_FORMAT_UBC1_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_UBC1 | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,

	PSP2_GXM_TEXTURE_FORMAT_UBC2_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_UBC2 | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,

	PSP2_GXM_TEXTURE_FORMAT_UBC3_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_UBC3 | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,

	PSP2_GXM_TEXTURE_FORMAT_YUV420P2_CSC0 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV420P2 | PSP2_GXM_TEXTURE_SWIZZLE_YUV_CSC0,
	PSP2_GXM_TEXTURE_FORMAT_YVU420P2_CSC0 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV420P2 | PSP2_GXM_TEXTURE_SWIZZLE_YVU_CSC0,
	PSP2_GXM_TEXTURE_FORMAT_YUV420P2_CSC1 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV420P2 | PSP2_GXM_TEXTURE_SWIZZLE_YUV_CSC1,
	PSP2_GXM_TEXTURE_FORMAT_YVU420P2_CSC1 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV420P2 | PSP2_GXM_TEXTURE_SWIZZLE_YVU_CSC1,

	PSP2_GXM_TEXTURE_FORMAT_YUV420P3_CSC0 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV420P3 | PSP2_GXM_TEXTURE_SWIZZLE_YUV_CSC0,
	PSP2_GXM_TEXTURE_FORMAT_YVU420P3_CSC0 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV420P3 | PSP2_GXM_TEXTURE_SWIZZLE_YVU_CSC0,
	PSP2_GXM_TEXTURE_FORMAT_YUV420P3_CSC1 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV420P3 | PSP2_GXM_TEXTURE_SWIZZLE_YUV_CSC1,
	PSP2_GXM_TEXTURE_FORMAT_YVU420P3_CSC1 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV420P3 | PSP2_GXM_TEXTURE_SWIZZLE_YVU_CSC1,

	PSP2_GXM_TEXTURE_FORMAT_YUYV422_CSC0 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV422 | PSP2_GXM_TEXTURE_SWIZZLE_YUYV_CSC0,
	PSP2_GXM_TEXTURE_FORMAT_YVYU422_CSC0 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV422 | PSP2_GXM_TEXTURE_SWIZZLE_YVYU_CSC0,
	PSP2_GXM_TEXTURE_FORMAT_UYVY422_CSC0 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV422 | PSP2_GXM_TEXTURE_SWIZZLE_UYVY_CSC0,
	PSP2_GXM_TEXTURE_FORMAT_VYUY422_CSC0 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV422 | PSP2_GXM_TEXTURE_SWIZZLE_VYUY_CSC0,
	PSP2_GXM_TEXTURE_FORMAT_YUYV422_CSC1 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV422 | PSP2_GXM_TEXTURE_SWIZZLE_YUYV_CSC1,
	PSP2_GXM_TEXTURE_FORMAT_YVYU422_CSC1 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV422 | PSP2_GXM_TEXTURE_SWIZZLE_YVYU_CSC1,
	PSP2_GXM_TEXTURE_FORMAT_UYVY422_CSC1 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV422 | PSP2_GXM_TEXTURE_SWIZZLE_UYVY_CSC1,
	PSP2_GXM_TEXTURE_FORMAT_VYUY422_CSC1 = PSP2_GXM_TEXTURE_BASE_FORMAT_YUV422 | PSP2_GXM_TEXTURE_SWIZZLE_VYUY_CSC1,

	PSP2_GXM_TEXTURE_FORMAT_P4_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_P4 | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_P4_ARGB = PSP2_GXM_TEXTURE_BASE_FORMAT_P4 | PSP2_GXM_TEXTURE_SWIZZLE4_ARGB,
	PSP2_GXM_TEXTURE_FORMAT_P4_RGBA = PSP2_GXM_TEXTURE_BASE_FORMAT_P4 | PSP2_GXM_TEXTURE_SWIZZLE4_RGBA,
	PSP2_GXM_TEXTURE_FORMAT_P4_BGRA = PSP2_GXM_TEXTURE_BASE_FORMAT_P4 | PSP2_GXM_TEXTURE_SWIZZLE4_BGRA,
	PSP2_GXM_TEXTURE_FORMAT_P4_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_P4 | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,
	PSP2_GXM_TEXTURE_FORMAT_P4_1RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_P4 | PSP2_GXM_TEXTURE_SWIZZLE4_1RGB,
	PSP2_GXM_TEXTURE_FORMAT_P4_RGB1 = PSP2_GXM_TEXTURE_BASE_FORMAT_P4 | PSP2_GXM_TEXTURE_SWIZZLE4_RGB1,
	PSP2_GXM_TEXTURE_FORMAT_P4_BGR1 = PSP2_GXM_TEXTURE_BASE_FORMAT_P4 | PSP2_GXM_TEXTURE_SWIZZLE4_BGR1,

	PSP2_GXM_TEXTURE_FORMAT_P8_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_P8 | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_P8_ARGB = PSP2_GXM_TEXTURE_BASE_FORMAT_P8 | PSP2_GXM_TEXTURE_SWIZZLE4_ARGB,
	PSP2_GXM_TEXTURE_FORMAT_P8_RGBA = PSP2_GXM_TEXTURE_BASE_FORMAT_P8 | PSP2_GXM_TEXTURE_SWIZZLE4_RGBA,
	PSP2_GXM_TEXTURE_FORMAT_P8_BGRA = PSP2_GXM_TEXTURE_BASE_FORMAT_P8 | PSP2_GXM_TEXTURE_SWIZZLE4_BGRA,
	PSP2_GXM_TEXTURE_FORMAT_P8_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_P8 | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,
	PSP2_GXM_TEXTURE_FORMAT_P8_1RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_P8 | PSP2_GXM_TEXTURE_SWIZZLE4_1RGB,
	PSP2_GXM_TEXTURE_FORMAT_P8_RGB1 = PSP2_GXM_TEXTURE_BASE_FORMAT_P8 | PSP2_GXM_TEXTURE_SWIZZLE4_RGB1,
	PSP2_GXM_TEXTURE_FORMAT_P8_BGR1 = PSP2_GXM_TEXTURE_BASE_FORMAT_P8 | PSP2_GXM_TEXTURE_SWIZZLE4_BGR1,

	PSP2_GXM_TEXTURE_FORMAT_U8U8U8_BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8U8 | PSP2_GXM_TEXTURE_SWIZZLE3_BGR,
	PSP2_GXM_TEXTURE_FORMAT_U8U8U8_RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U8U8U8 | PSP2_GXM_TEXTURE_SWIZZLE3_RGB,

	PSP2_GXM_TEXTURE_FORMAT_S8S8S8_BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8S8 | PSP2_GXM_TEXTURE_SWIZZLE3_BGR,
	PSP2_GXM_TEXTURE_FORMAT_S8S8S8_RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_S8S8S8 | PSP2_GXM_TEXTURE_SWIZZLE3_RGB,

	PSP2_GXM_TEXTURE_FORMAT_U2F10F10F10_ABGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U2F10F10F10 | PSP2_GXM_TEXTURE_SWIZZLE4_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_U2F10F10F10_ARGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U2F10F10F10 | PSP2_GXM_TEXTURE_SWIZZLE4_ARGB,
	PSP2_GXM_TEXTURE_FORMAT_F10F10F10U2_RGBA = PSP2_GXM_TEXTURE_BASE_FORMAT_U2F10F10F10 | PSP2_GXM_TEXTURE_SWIZZLE4_RGBA,
	PSP2_GXM_TEXTURE_FORMAT_F10F10F10U2_BGRA = PSP2_GXM_TEXTURE_BASE_FORMAT_U2F10F10F10 | PSP2_GXM_TEXTURE_SWIZZLE4_BGRA,
	PSP2_GXM_TEXTURE_FORMAT_X2F10F10F10_1BGR = PSP2_GXM_TEXTURE_BASE_FORMAT_U2F10F10F10 | PSP2_GXM_TEXTURE_SWIZZLE4_1BGR,
	PSP2_GXM_TEXTURE_FORMAT_X2F10F10F10_1RGB = PSP2_GXM_TEXTURE_BASE_FORMAT_U2F10F10F10 | PSP2_GXM_TEXTURE_SWIZZLE4_1RGB,
	PSP2_GXM_TEXTURE_FORMAT_F10F10F10X2_RGB1 = PSP2_GXM_TEXTURE_BASE_FORMAT_U2F10F10F10 | PSP2_GXM_TEXTURE_SWIZZLE4_RGB1,
	PSP2_GXM_TEXTURE_FORMAT_F10F10F10X2_BGR1 = PSP2_GXM_TEXTURE_BASE_FORMAT_U2F10F10F10 | PSP2_GXM_TEXTURE_SWIZZLE4_BGR1,

	// Legacy formats

	PSP2_GXM_TEXTURE_FORMAT_L8 = PSP2_GXM_TEXTURE_FORMAT_U8_1RRR,
	PSP2_GXM_TEXTURE_FORMAT_A8 = PSP2_GXM_TEXTURE_FORMAT_U8_R000,
	PSP2_GXM_TEXTURE_FORMAT_R8 = PSP2_GXM_TEXTURE_FORMAT_U8_000R,
	PSP2_GXM_TEXTURE_FORMAT_A4R4G4B4 = PSP2_GXM_TEXTURE_FORMAT_U4U4U4U4_ARGB,
	PSP2_GXM_TEXTURE_FORMAT_A1R5G5B5 = PSP2_GXM_TEXTURE_FORMAT_U1U5U5U5_ARGB,
	PSP2_GXM_TEXTURE_FORMAT_R5G6B5 = PSP2_GXM_TEXTURE_FORMAT_U5U6U5_RGB,
	PSP2_GXM_TEXTURE_FORMAT_A8L8 = PSP2_GXM_TEXTURE_FORMAT_U8U8_GRRR,
	PSP2_GXM_TEXTURE_FORMAT_L8A8 = PSP2_GXM_TEXTURE_FORMAT_U8U8_RGGG,
	PSP2_GXM_TEXTURE_FORMAT_G8R8 = PSP2_GXM_TEXTURE_FORMAT_U8U8_00GR,
	PSP2_GXM_TEXTURE_FORMAT_L16 = PSP2_GXM_TEXTURE_FORMAT_U16_1RRR,
	PSP2_GXM_TEXTURE_FORMAT_A16 = PSP2_GXM_TEXTURE_FORMAT_U16_R000,
	PSP2_GXM_TEXTURE_FORMAT_R16 = PSP2_GXM_TEXTURE_FORMAT_U16_000R,
	PSP2_GXM_TEXTURE_FORMAT_D16 = PSP2_GXM_TEXTURE_FORMAT_U16_R,
	PSP2_GXM_TEXTURE_FORMAT_LF16 = PSP2_GXM_TEXTURE_FORMAT_F16_1RRR,
	PSP2_GXM_TEXTURE_FORMAT_AF16 = PSP2_GXM_TEXTURE_FORMAT_F16_R000,
	PSP2_GXM_TEXTURE_FORMAT_RF16 = PSP2_GXM_TEXTURE_FORMAT_F16_000R,
	PSP2_GXM_TEXTURE_FORMAT_A8R8G8B8 = PSP2_GXM_TEXTURE_FORMAT_U8U8U8U8_ARGB,
	PSP2_GXM_TEXTURE_FORMAT_A8B8G8R8 = PSP2_GXM_TEXTURE_FORMAT_U8U8U8U8_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_AF16LF16 = PSP2_GXM_TEXTURE_FORMAT_F16F16_GRRR,
	PSP2_GXM_TEXTURE_FORMAT_LF16AF16 = PSP2_GXM_TEXTURE_FORMAT_F16F16_RGGG,
	PSP2_GXM_TEXTURE_FORMAT_GF16RF16 = PSP2_GXM_TEXTURE_FORMAT_F16F16_00GR,
	PSP2_GXM_TEXTURE_FORMAT_LF32M = PSP2_GXM_TEXTURE_FORMAT_F32M_1RRR,
	PSP2_GXM_TEXTURE_FORMAT_AF32M = PSP2_GXM_TEXTURE_FORMAT_F32M_R000,
	PSP2_GXM_TEXTURE_FORMAT_RF32M = PSP2_GXM_TEXTURE_FORMAT_F32M_000R,
	PSP2_GXM_TEXTURE_FORMAT_DF32M = PSP2_GXM_TEXTURE_FORMAT_F32M_R,
	PSP2_GXM_TEXTURE_FORMAT_VYUY = PSP2_GXM_TEXTURE_FORMAT_VYUY422_CSC0,
	PSP2_GXM_TEXTURE_FORMAT_YVYU = PSP2_GXM_TEXTURE_FORMAT_YVYU422_CSC0,
	PSP2_GXM_TEXTURE_FORMAT_UBC1 = PSP2_GXM_TEXTURE_FORMAT_UBC1_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_UBC2 = PSP2_GXM_TEXTURE_FORMAT_UBC2_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_UBC3 = PSP2_GXM_TEXTURE_FORMAT_UBC3_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_PVRT2BPP = PSP2_GXM_TEXTURE_FORMAT_PVRT2BPP_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_PVRT4BPP = PSP2_GXM_TEXTURE_FORMAT_PVRT4BPP_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_PVRTII2BPP = PSP2_GXM_TEXTURE_FORMAT_PVRTII2BPP_ABGR,
	PSP2_GXM_TEXTURE_FORMAT_PVRTII4BPP = PSP2_GXM_TEXTURE_FORMAT_PVRTII4BPP_ABGR
} SceGxmTextureFormat;

typedef enum SceGxmTextureAnisoMode {
	PSP2_GXM_TEXTURE_ANISO_DISABLED	= 0x00000000u,
	PSP2_GXM_TEXTURE_ANISO_ENABLED	= 0x00004000u
} SceGxmTextureAnisoMode;

typedef enum SceGxmTextureType {
	PSP2_GXM_TEXTURE_SWIZZLED	= 0x00000000u,
	PSP2_GXM_TEXTURE_CUBE		= 0x40000000u,
	PSP2_GXM_TEXTURE_LINEAR		= 0x60000000u,
	PSP2_GXM_TEXTURE_TILED		= 0x80000000u,
	PSP2_GXM_TEXTURE_LINEAR_STRIDED	= 0xc0000000u
} SceGxmTextureType;

typedef enum SceGxmTextureFilter {
	PSP2_GXM_TEXTURE_FILTER_POINT	= 0x00000000u,
	PSP2_GXM_TEXTURE_FILTER_LINEAR	= 0x00000001u,
	PSP2_GXM_TEXTURE_FILTER_ANISO_LINEAR	= 0x00000002u,
	PSP2_GXM_TEXTURE_FILTER_ANISO_POINT	= 0x00000003u
} SceGxmTextureFilter;

typedef enum SceGxmTextureMipFilter {
	PSP2_GXM_TEXTURE_MIP_FILTER_DISABLED	= 0x00000000u,
	PSP2_GXM_TEXTURE_MIP_FILTER_ENABLED	= 0x00000200u
} SceGxmTextureMipFilter;

typedef enum SceGxmTextureAddrMode {
	PSP2_GXM_TEXTURE_ADDR_REPEAT			= 0x00000000u,
	PSP2_GXM_TEXTURE_ADDR_MIRROR			= 0x00000001u,
	PSP2_GXM_TEXTURE_ADDR_CLAMP			= 0x00000002u,
	PSP2_GXM_TEXTURE_ADDR_MIRROR_CLAMP		= 0x00000003u,
	PSP2_GXM_TEXTURE_ADDR_REPEAT_IGNORE_BORDER	= 0x00000004u,
	PSP2_GXM_TEXTURE_ADDR_CLAMP_FULL_BORDER		= 0x00000005u,
	PSP2_GXM_TEXTURE_ADDR_CLAMP_IGNORE_BORDER	= 0x00000006u,
	PSP2_GXM_TEXTURE_ADDR_CLAMP_HALF_BORDER		= 0x00000007u
} SceGxmTextureAddrMode;

typedef enum SceGxmTextureGammaMode {
	PSP2_GXM_TEXTURE_GAMMA_NONE	= 0x00000000u,
	PSP2_GXM_TEXTURE_GAMMA_R		= 0x08000000u,
	PSP2_GXM_TEXTURE_GAMMA_GR	= 0x18000000u,
	PSP2_GXM_TEXTURE_GAMMA_BGR	= 0x08000000u
} SceGxmTextureGammaMode;

typedef enum SceGxmIndexFormat {
	PSP2_GXM_INDEX_FORMAT_U16	= 0x00000000u,
	PSP2_GXM_INDEX_FORMAT_U32	= 0x01000000u
} SceGxmIndexFormat;

typedef enum SceGxmIndexSource {
	PSP2_GXM_INDEX_SOURCE_INDEX_16BIT	= 0x00000000u,
	PSP2_GXM_INDEX_SOURCE_INDEX_32BIT	= 0x00000001u,
	PSP2_GXM_INDEX_SOURCE_INSTANCE_16BIT	= 0x00000002u,
	PSP2_GXM_INDEX_SOURCE_INSTANCE_32BIT	= 0x00000003u
} SceGxmIndexSource;

typedef enum SceGxmFragmentProgramMode {
	PSP2_GXM_FRAGMENT_PROGRAM_DISABLED	= 0x00200000u,
	PSP2_GXM_FRAGMENT_PROGRAM_ENABLED	= 0x00000000u
} SceGxmFragmentProgramMode;

typedef enum SceGxmDepthWriteMode {
	PSP2_GXM_DEPTH_WRITE_DISABLED	= 0x00100000u,
	PSP2_GXM_DEPTH_WRITE_ENABLED	= 0x00000000u
} SceGxmDepthWriteMode;

typedef enum SceGxmLineFillLastPixelMode {
	PSP2_GXM_LINE_FILL_LAST_PIXEL_DISABLED	= 0x00000000u,
	PSP2_GXM_LINE_FILL_LAST_PIXEL_ENABLED	= 0x00080000u
} SceGxmLineFillLastPixelMode;

typedef enum SceGxmTwoSidedMode {
	PSP2_GXM_TWO_SIDED_DISABLED	= 0x00000000u,
	PSP2_GXM_TWO_SIDED_ENABLED	= 0x00000800u
} SceGxmTwoSidedMode;

typedef enum SceGxmWClampMode {
	PSP2_GXM_WCLAMP_MODE_DISABLED	= 0x00000000u,
	PSP2_GXM_WCLAMP_MODE_ENABLED	= 0x00008000u
} SceGxmWClampMode;

typedef enum SceGxmViewportMode {
	PSP2_GXM_VIEWPORT_DISABLED	= 0x00010000u,
	PSP2_GXM_VIEWPORT_ENABLED	= 0x00000000u
} SceGxmViewportMode;

typedef enum SceGxmWBufferMode {
	PSP2_GXM_WBUFFER_DISABLED	= 0x00000000u,
	PSP2_GXM_WBUFFER_ENABLED		= 0x00004000u
} SceGxmWBufferMode;

typedef enum SceGxmDepthStencilForceLoadMode {
	PSP2_GXM_DEPTH_STENCIL_FORCE_LOAD_DISABLED	= 0x00000000u,
	PSP2_GXM_DEPTH_STENCIL_FORCE_LOAD_ENABLED	= 0x00000002u
} SceGxmDepthStencilForceLoadMode;

typedef enum SceGxmDepthStencilForceStoreMode {
	PSP2_GXM_DEPTH_STENCIL_FORCE_STORE_DISABLED	= 0x00000000u,
	PSP2_GXM_DEPTH_STENCIL_FORCE_STORE_ENABLED	= 0x00000004u
} SceGxmDepthStencilForceStoreMode;

typedef enum SceGxmSceneFlags {
	PSP2_GXM_SCENE_FRAGMENT_SET_DEPENDENCY		= 0x00000001u,
	PSP2_GXM_SCENE_VERTEX_WAIT_FOR_DEPENDENCY	= 0x00000002u
} SceGxmSceneFlags;

typedef enum SceGxmMidSceneFlags {
	PSP2_GXM_MIDSCENE_PRESERVE_DEFAULT_UNIFORM_BUFFERS	= 0x00000001u
} SceGxmMidSceneFlags;

typedef enum SceGxmColorSurfaceScaleMode {
	PSP2_GXM_COLOR_SURFACE_SCALE_NONE		= 0x00000000u,
	PSP2_GXM_COLOR_SURFACE_SCALE_MSAA_DOWNSCALE	= 0x00000001u
} SceGxmColorSurfaceScaleMode;

typedef enum SceGxmOutputRegisterSize {
	PSP2_GXM_OUTPUT_REGISTER_SIZE_32BIT	= 0x00000000u,
	PSP2_GXM_OUTPUT_REGISTER_SIZE_64BIT	= 0x00000001u
} SceGxmOutputRegisterSize;

typedef enum SceGxmVisibilityTestMode {
	PSP2_GXM_VISIBILITY_TEST_DISABLED	= 0x00000000u,
	PSP2_GXM_VISIBILITY_TEST_ENABLED		= 0x00004000u
} SceGxmVisibilityTestMode;

typedef enum SceGxmVisibilityTestOp {
	PSP2_GXM_VISIBILITY_TEST_OP_INCREMENT	= 0x00000000u,
	PSP2_GXM_VISIBILITY_TEST_OP_SET		= 0x00040000u
} SceGxmVisibilityTestOp;

typedef enum SceGxmBlendFunc {
	PSP2_GXM_BLEND_FUNC_NONE,
	PSP2_GXM_BLEND_FUNC_ADD,
	PSP2_GXM_BLEND_FUNC_SUBTRACT,
	PSP2_GXM_BLEND_FUNC_REVERSE_SUBTRACT
} SceGxmBlendFunc;

typedef enum SceGxmBlendFactor {
	PSP2_GXM_BLEND_FACTOR_ZERO,
	PSP2_GXM_BLEND_FACTOR_ONE,
	PSP2_GXM_BLEND_FACTOR_SRC_COLOR,
	PSP2_GXM_BLEND_FACTOR_ONE_MINUS_SRC_COLOR,
	PSP2_GXM_BLEND_FACTOR_SRC_ALPHA,
	PSP2_GXM_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
	PSP2_GXM_BLEND_FACTOR_DST_COLOR,
	PSP2_GXM_BLEND_FACTOR_ONE_MINUS_DST_COLOR,
	PSP2_GXM_BLEND_FACTOR_DST_ALPHA,
	PSP2_GXM_BLEND_FACTOR_ONE_MINUS_DST_ALPHA,
	PSP2_GXM_BLEND_FACTOR_SRC_ALPHA_SATURATE,
	PSP2_GXM_BLEND_FACTOR_DST_ALPHA_SATURATE
} SceGxmBlendFactor;

typedef enum SceGxmColorMask {
	PSP2_GXM_COLOR_MASK_NONE	= 0,
	PSP2_GXM_COLOR_MASK_A	= (1 << 0),
	PSP2_GXM_COLOR_MASK_R	= (1 << 1),
	PSP2_GXM_COLOR_MASK_G	= (1 << 2),
	PSP2_GXM_COLOR_MASK_B	= (1 << 3),
	PSP2_GXM_COLOR_MASK_ALL	= (PSP2_GXM_COLOR_MASK_A | PSP2_GXM_COLOR_MASK_B | PSP2_GXM_COLOR_MASK_G | PSP2_GXM_COLOR_MASK_R)
} SceGxmColorMask;

typedef struct SceGxmBlendInfo {
	SceGxmColorMask colorMask;
	SceGxmBlendFunc colorFunc : 4;
	SceGxmBlendFunc alphaFunc : 4;
	SceGxmBlendFactor colorSrc : 4;
	SceGxmBlendFactor colorDst : 4;
	SceGxmBlendFactor alphaSrc : 4;
	SceGxmBlendFactor alphaDst : 4;
} SceGxmBlendInfo;

typedef struct SceGxmRenderTarget SceGxmRenderTarget;

typedef struct SceGxmSyncObject SceGxmSyncObject;

typedef struct SceGxmVertexAttribute {
	unsigned short streamIndex;
	unsigned short offset;
	SceGxmAttributeFormat format;
	unsigned char componentCount;
	unsigned short regIndex;
} SceGxmVertexAttribute;

typedef struct SceGxmVertexStream {
	unsigned short stride;
	unsigned short indexSource;
} SceGxmVertexStream;

typedef struct SceGxmTexture {
	unsigned int controlWords[4];
} SceGxmTexture;

typedef struct SceGxmColorSurface {
	unsigned int pbeSidebandWord;
	unsigned int pbeEmitWords[6];
	unsigned int outputRegisterSize;
	SceGxmTexture backgroundTex;
} SceGxmColorSurface;

typedef struct SceGxmDepthStencilSurface {
	unsigned int zlsControl;
	void *depthData;
	void *stencilData;
	float backgroundDepth;
	unsigned int backgroundControl;
} SceGxmDepthStencilSurface;

//! Represents an auxiliary surface
typedef struct SceGxmAuxiliarySurface {
	uint32_t colorFormat; //!< Format of auxiliary surface data from SceGxmColorFormat
	uint32_t type; //!< Memory layout of the surface data from SceGxmColorSurfaceType
	uint32_t width; //!< Surface width
	uint32_t height; //!< Surface height
	uint32_t stride; //!< Surface stride in bytes
	void *data; //!< A pointer to the surface data
} SceGxmAuxiliarySurface;

typedef struct SceGxmNotification {
	volatile unsigned int *address;
	unsigned int value;
} SceGxmNotification;

typedef struct SceGxmValidRegion {
	unsigned int xMin;
	unsigned int yMin;
	unsigned int xMax;
	unsigned int yMax;
} SceGxmValidRegion;

typedef struct SceGxmContext SceGxmContext;

enum {
	PSP2_GXM_MINIMUM_CONTEXT_HOST_MEM_SIZE		= 2048,
	PSP2_GXM_DEFAULT_VDM_RING_BUFFER_SIZE		= (128 * 1024),
	PSP2_GXM_DEFAULT_VERTEX_RING_BUFFER_SIZE		= (2 * 1024 * 1024),
	PSP2_GXM_DEFAULT_FRAGMENT_RING_BUFFER_SIZE	= (512 * 1024),
	PSP2_GXM_DEFAULT_FRAGMENT_USSE_RING_BUFFER_SIZE	= (16 * 1024),
};

typedef struct SceGxmContextParams {
	void *hostMem;
	SceSize hostMemSize;
	void *vdmRingBufferMem;
	SceSize vdmRingBufferMemSize;
	void *vertexRingBufferMem;
	SceSize vertexRingBufferMemSize;
	void *fragmentRingBufferMem;
	SceSize fragmentRingBufferMemSize;
	void *fragmentUsseRingBufferMem;
	SceSize fragmentUsseRingBufferMemSize;
	unsigned int fragmentUsseRingBufferOffset;
} SceGxmContextParams;

typedef struct SceGxmVertexProgram SceGxmVertexProgram;

typedef struct SceGxmFragmentProgram SceGxmFragmentProgram;

enum {
	PSP2_GXM_PRECOMPUTED_VERTEX_STATE_WORD_COUNT   = 7,
	PSP2_GXM_PRECOMPUTED_FRAGMENT_STATE_WORD_COUNT = 9,
	PSP2_GXM_PRECOMPUTED_DRAW_WORD_COUNT           = 11,
};

typedef struct SceGxmPrecomputedVertexState {
	unsigned int data[PSP2_GXM_PRECOMPUTED_VERTEX_STATE_WORD_COUNT];
} SceGxmPrecomputedVertexState;

typedef struct SceGxmPrecomputedFragmentState {
	unsigned int data[PSP2_GXM_PRECOMPUTED_FRAGMENT_STATE_WORD_COUNT];
} SceGxmPrecomputedFragmentState;

typedef struct SceGxmPrecomputedDraw {
	unsigned int data[PSP2_GXM_PRECOMPUTED_DRAW_WORD_COUNT];
} SceGxmPrecomputedDraw;

enum {
	PSP2_GXM_MAX_VERTEX_ATTRIBUTES  = 16,
	PSP2_GXM_MAX_VERTEX_STREAMS     = 4,
	PSP2_GXM_MAX_TEXTURE_UNITS      = 16,
	PSP2_GXM_MAX_UNIFORM_BUFFERS    = 8,
	PSP2_GXM_MAX_AUXILIARY_SURFACES = 3,
};

typedef struct SceGxmProgram SceGxmProgram;

typedef struct SceGxmProgramParameter SceGxmProgramParameter;

typedef enum SceGxmProgramType {
	PSP2_GXM_VERTEX_PROGRAM,
	PSP2_GXM_FRAGMENT_PROGRAM
} SceGxmProgramType;

typedef enum SceGxmParameterCategory {
	PSP2_GXM_PARAMETER_CATEGORY_ATTRIBUTE,
	PSP2_GXM_PARAMETER_CATEGORY_UNIFORM,
	PSP2_GXM_PARAMETER_CATEGORY_SAMPLER,
	PSP2_GXM_PARAMETER_CATEGORY_AUXILIARY_SURFACE,
	PSP2_GXM_PARAMETER_CATEGORY_UNIFORM_BUFFER
} SceGxmParameterCategory;

typedef enum SceGxmParameterType {
	PSP2_GXM_PARAMETER_TYPE_F32,
	PSP2_GXM_PARAMETER_TYPE_F16,
	PSP2_GXM_PARAMETER_TYPE_C10,
	PSP2_GXM_PARAMETER_TYPE_U32,
	PSP2_GXM_PARAMETER_TYPE_S32,
	PSP2_GXM_PARAMETER_TYPE_U16,
	PSP2_GXM_PARAMETER_TYPE_S16,
	PSP2_GXM_PARAMETER_TYPE_U8,
	PSP2_GXM_PARAMETER_TYPE_S8,
	PSP2_GXM_PARAMETER_TYPE_AGGREGATE
} SceGxmParameterType;

typedef enum SceGxmParameterSemantic {
	PSP2_GXM_PARAMETER_SEMANTIC_NONE,
	PSP2_GXM_PARAMETER_SEMANTIC_ATTR,
	PSP2_GXM_PARAMETER_SEMANTIC_BCOL,
	PSP2_GXM_PARAMETER_SEMANTIC_BINORMAL,
	PSP2_GXM_PARAMETER_SEMANTIC_BLENDINDICES,
	PSP2_GXM_PARAMETER_SEMANTIC_BLENDWEIGHT,
	PSP2_GXM_PARAMETER_SEMANTIC_COLOR,
	PSP2_GXM_PARAMETER_SEMANTIC_DIFFUSE,
	PSP2_GXM_PARAMETER_SEMANTIC_FOGCOORD,
	PSP2_GXM_PARAMETER_SEMANTIC_NORMAL,
	PSP2_GXM_PARAMETER_SEMANTIC_POINTSIZE,
	PSP2_GXM_PARAMETER_SEMANTIC_POSITION,
	PSP2_GXM_PARAMETER_SEMANTIC_SPECULAR,
	PSP2_GXM_PARAMETER_SEMANTIC_TANGENT,
	PSP2_GXM_PARAMETER_SEMANTIC_TEXCOORD
} SceGxmParameterSemantic;

typedef struct SceGxmShaderPatcher SceGxmShaderPatcher;

typedef struct SceGxmRegisteredProgram SceGxmRegisteredProgram;

typedef SceGxmRegisteredProgram *SceGxmShaderPatcherId;

typedef void *(SceGxmShaderPatcherHostAllocCallback)(void *userData, SceSize size);
typedef void (SceGxmShaderPatcherHostFreeCallback)(void *userData, void *mem);
typedef void *(SceGxmShaderPatcherBufferAllocCallback)(void *userData, SceSize size);
typedef void (SceGxmShaderPatcherBufferFreeCallback)(void *userData, void *mem);
typedef void *(SceGxmShaderPatcherUsseAllocCallback)(void *userData, SceSize size, unsigned int *usseOffset);
typedef void (SceGxmShaderPatcherUsseFreeCallback)(void *userData, void *mem);

typedef struct SceGxmShaderPatcherParams {
	void *userData;
	SceGxmShaderPatcherHostAllocCallback *hostAllocCallback;
	SceGxmShaderPatcherHostFreeCallback *hostFreeCallback;
	SceGxmShaderPatcherBufferAllocCallback *bufferAllocCallback;
	SceGxmShaderPatcherBufferFreeCallback *bufferFreeCallback;
	void *bufferMem;
	SceSize bufferMemSize;
	SceGxmShaderPatcherUsseAllocCallback *vertexUsseAllocCallback;
	SceGxmShaderPatcherUsseFreeCallback *vertexUsseFreeCallback;
	void *vertexUsseMem;
	SceSize vertexUsseMemSize;
	unsigned int vertexUsseOffset;
	SceGxmShaderPatcherUsseAllocCallback *fragmentUsseAllocCallback;
	SceGxmShaderPatcherUsseFreeCallback *fragmentUsseFreeCallback;
	void *fragmentUsseMem;
	SceSize fragmentUsseMemSize;
	unsigned int fragmentUsseOffset;
} SceGxmShaderPatcherParams;

typedef enum SceGxmRenderTargetFlags {
	PSP2_GXM_RENDER_TARGET_CUSTOM_MULTISAMPLE_LOCATIONS = (1 << 0),
} SceGxmRenderTargetFlags;

typedef struct SceGxmRenderTargetParams {
	SceGxmRenderTargetFlags flags;
	unsigned short width;
	unsigned short height;
	unsigned short scenesPerFrame;
	SceGxmMultisampleMode multisampleMode;
	unsigned int multisampleLocations;
	void *hostMem;
	SceSize hostMemSize;
	int driverMemBlock;
} SceGxmRenderTargetParams;

/* prototypes */

int sceGxmInitialize(const SceGxmInitializeParams *params);
int sceGxmTerminate();

volatile unsigned int *sceGxmGetNotificationRegion();
int sceGxmNotificationWait(const SceGxmNotification *notification);

int sceGxmMapMemory(void *base, SceSize size, SceGxmMemoryAttribFlags attr);
int sceGxmUnmapMemory(void *base);

int sceGxmMapVertexUsseMemory(void *base, SceSize size, unsigned int *offset);
int sceGxmUnmapVertexUsseMemory(void *base);

int sceGxmMapFragmentUsseMemory(void *base, SceSize size, unsigned int *offset);
int sceGxmUnmapFragmentUsseMemory(void *base);

int sceGxmDisplayQueueAddEntry(SceGxmSyncObject *oldBuffer, SceGxmSyncObject *newBuffer, const void *callbackData);
int sceGxmDisplayQueueFinish();

int sceGxmSyncObjectCreate(SceGxmSyncObject **syncObject);
int sceGxmSyncObjectDestroy(SceGxmSyncObject *syncObject);

int sceGxmCreateContext(const SceGxmContextParams *params, SceGxmContext **context);
int sceGxmDestroyContext(SceGxmContext *context);

void sceGxmSetValidationEnable(SceGxmContext *context, SceBool enable);

void sceGxmSetVertexProgram(SceGxmContext *context, const SceGxmVertexProgram *vertexProgram);
void sceGxmSetFragmentProgram(SceGxmContext *context, const SceGxmFragmentProgram *fragmentProgram);

int sceGxmReserveVertexDefaultUniformBuffer(SceGxmContext *context, void **uniformBuffer);
int sceGxmReserveFragmentDefaultUniformBuffer(SceGxmContext *context, void **uniformBuffer);

int sceGxmSetVertexStream(SceGxmContext *context, unsigned int streamIndex, const void *streamData);
int sceGxmSetVertexTexture(SceGxmContext *context, unsigned int textureIndex, const SceGxmTexture *texture);
int sceGxmSetFragmentTexture(SceGxmContext *context, unsigned int textureIndex, const SceGxmTexture *texture);
int sceGxmSetVertexUniformBuffer(SceGxmContext *context, unsigned int bufferIndex, const void *bufferData);
int sceGxmSetFragmentUniformBuffer(SceGxmContext *context, unsigned int bufferIndex, const void *bufferData);
int sceGxmSetAuxiliarySurface(SceGxmContext *context, unsigned int surfaceIndex, const SceGxmAuxiliarySurface *surface);

void sceGxmSetPrecomputedFragmentState(SceGxmContext *context, const SceGxmPrecomputedFragmentState *precomputedState);
void sceGxmSetPrecomputedVertexState(SceGxmContext *context, const SceGxmPrecomputedVertexState *precomputedState);

int sceGxmDrawPrecomputed(SceGxmContext *context, const SceGxmPrecomputedDraw *precomputedDraw);
int sceGxmDraw(SceGxmContext *context, SceGxmPrimitiveType primType, SceGxmIndexFormat indexType, const void *indexData, unsigned int indexCount);
int sceGxmDrawInstanced(SceGxmContext *context, SceGxmPrimitiveType primType, SceGxmIndexFormat indexType, const void *indexData, unsigned int indexCount, unsigned int indexWrap);
int sceGxmSetVisibilityBuffer(SceGxmContext *context, void *bufferBase, unsigned int stridePerCore);

int sceGxmBeginScene(SceGxmContext *context, unsigned int flags, const SceGxmRenderTarget *renderTarget, const SceGxmValidRegion *validRegion, SceGxmSyncObject *vertexSyncObject, SceGxmSyncObject *fragmentSyncObject, const SceGxmColorSurface *colorSurface, const SceGxmDepthStencilSurface *depthStencil);
int sceGxmMidSceneFlush(SceGxmContext *context, unsigned int flags, SceGxmSyncObject *vertexSyncObject, const SceGxmNotification *vertexNotification);
int sceGxmEndScene(SceGxmContext *context, const SceGxmNotification *vertexNotification, const SceGxmNotification *fragmentNotification);

void sceGxmSetFrontDepthFunc(SceGxmContext *context, SceGxmDepthFunc depthFunc);
void sceGxmSetBackDepthFunc(SceGxmContext *context, SceGxmDepthFunc depthFunc);
void sceGxmSetFrontFragmentProgramEnable(SceGxmContext *context, SceGxmFragmentProgramMode enable);
void sceGxmSetBackFragmentProgramEnable(SceGxmContext *context, SceGxmFragmentProgramMode enable);
void sceGxmSetFrontDepthWriteEnable(SceGxmContext *context, SceGxmDepthWriteMode enable);
void sceGxmSetBackDepthWriteEnable(SceGxmContext *context, SceGxmDepthWriteMode enable);
void sceGxmSetFrontLineFillLastPixelEnable(SceGxmContext *context, SceGxmLineFillLastPixelMode enable);
void sceGxmSetBackLineFillLastPixelEnable(SceGxmContext *context, SceGxmLineFillLastPixelMode enable);
void sceGxmSetFrontStencilRef(SceGxmContext *context, unsigned int sref);
void sceGxmSetBackStencilRef(SceGxmContext *context, unsigned int sref);
void sceGxmSetFrontPointLineWidth(SceGxmContext *context, unsigned int width);
void sceGxmSetBackPointLineWidth(SceGxmContext *context, unsigned int width);
void sceGxmSetFrontPolygonMode(SceGxmContext *context, SceGxmPolygonMode mode);
void sceGxmSetBackPolygonMode(SceGxmContext *context, SceGxmPolygonMode mode);
void sceGxmSetFrontStencilFunc(SceGxmContext *context, SceGxmStencilFunc func, SceGxmStencilOp stencilFail, SceGxmStencilOp depthFail, SceGxmStencilOp depthPass, unsigned char compareMask, unsigned char writeMask);
void sceGxmSetBackStencilFunc(SceGxmContext *context, SceGxmStencilFunc func, SceGxmStencilOp stencilFail, SceGxmStencilOp depthFail, SceGxmStencilOp depthPass, unsigned char compareMask, unsigned char writeMask);
void sceGxmSetFrontDepthBias(SceGxmContext *context, int factor, int units);
void sceGxmSetBackDepthBias(SceGxmContext *context, int factor, int units);
void sceGxmSetTwoSidedEnable(SceGxmContext *context, SceGxmTwoSidedMode enable);
void sceGxmSetViewport(SceGxmContext *context, float xOffset, float xScale, float yOffset, float yScale, float zOffset, float zScale);
void sceGxmSetWClampValue(SceGxmContext *context, float clampValue);
void sceGxmSetWClampEnable(SceGxmContext *context, SceGxmWClampMode enable);
void sceGxmSetRegionClip(SceGxmContext *context, SceGxmRegionClipMode mode, unsigned int xMin, unsigned int yMin, unsigned int xMax, unsigned int yMax);
void sceGxmSetCullMode(SceGxmContext *context, SceGxmCullMode mode);
void sceGxmSetViewportEnable(SceGxmContext *context, SceGxmViewportMode enable);
void sceGxmSetWBufferEnable(SceGxmContext *context, SceGxmWBufferMode enable);
void sceGxmSetFrontVisibilityTestIndex(SceGxmContext *context, unsigned int index);
void sceGxmSetBackVisibilityTestIndex(SceGxmContext *context, unsigned int index);
void sceGxmSetFrontVisibilityTestOp(SceGxmContext *context, SceGxmVisibilityTestOp op);
void sceGxmSetBackVisibilityTestOp(SceGxmContext *context, SceGxmVisibilityTestOp op);
void sceGxmSetFrontVisibilityTestEnable(SceGxmContext *context, SceGxmVisibilityTestMode enable);
void sceGxmSetBackVisibilityTestEnable(SceGxmContext *context, SceGxmVisibilityTestMode enable);

void sceGxmFinish(SceGxmContext *context);

int sceGxmPushUserMarker(SceGxmContext *context, const char *tag);
int sceGxmPopUserMarker(SceGxmContext *context);
int sceGxmSetUserMarker(SceGxmContext *context, const char *tag);

int sceGxmPadHeartbeat(const SceGxmColorSurface *displaySurface, SceGxmSyncObject *displaySyncObject);

int sceGxmPadTriggerGpuPaTrace();

int sceGxmColorSurfaceInit(SceGxmColorSurface *surface, SceGxmColorFormat colorFormat, SceGxmColorSurfaceType surfaceType, SceGxmColorSurfaceScaleMode scaleMode, SceGxmOutputRegisterSize outputRegisterSize, unsigned int width, unsigned int height, unsigned int strideInPixels, void *data);
int sceGxmColorSurfaceInitDisabled(SceGxmColorSurface *surface);
SceBool sceGxmColorSurfaceIsEnabled(const SceGxmColorSurface *surface);
void sceGxmColorSurfaceGetClip(const SceGxmColorSurface *surface, unsigned int *xMin, unsigned int *yMin, unsigned int *xMax, unsigned int *yMax);
void sceGxmColorSurfaceSetClip(SceGxmColorSurface *surface, unsigned int xMin, unsigned int yMin, unsigned int xMax, unsigned int yMax);

SceGxmColorSurfaceScaleMode sceGxmColorSurfaceGetScaleMode(const SceGxmColorSurface *surface);
void sceGxmColorSurfaceSetScaleMode(SceGxmColorSurface *surface, SceGxmColorSurfaceScaleMode scaleMode);

void *sceGxmColorSurfaceGetData(const SceGxmColorSurface *surface);
int sceGxmColorSurfaceSetData(SceGxmColorSurface *surface, void *data);

SceGxmColorFormat sceGxmColorSurfaceGetFormat(const SceGxmColorSurface *surface);
int sceGxmColorSurfaceSetFormat(SceGxmColorSurface *surface, SceGxmColorFormat format);
SceGxmColorSurfaceType sceGxmColorSurfaceGetType(const SceGxmColorSurface *surface);
unsigned int sceGxmColorSurfaceGetStrideInPixels(const SceGxmColorSurface *surface);

int sceGxmDepthStencilSurfaceInit(SceGxmDepthStencilSurface *surface, SceGxmDepthStencilFormat depthStencilFormat, SceGxmDepthStencilSurfaceType surfaceType, unsigned int strideInSamples, void *depthData, void *stencilData);
int sceGxmDepthStencilSurfaceInitDisabled(SceGxmDepthStencilSurface *surface);
float sceGxmDepthStencilSurfaceGetBackgroundDepth(const SceGxmDepthStencilSurface *surface);
void sceGxmDepthStencilSurfaceSetBackgroundDepth(SceGxmDepthStencilSurface *surface, float backgroundDepth);
unsigned char sceGxmDepthStencilSurfaceGetBackgroundStencil(const SceGxmDepthStencilSurface *surface);
void sceGxmDepthStencilSurfaceSetBackgroundStencil(SceGxmDepthStencilSurface *surface, unsigned char backgroundStencil);
SceBool sceGxmDepthStencilSurfaceIsEnabled(const SceGxmDepthStencilSurface *surface);
void sceGxmDepthStencilSurfaceSetForceLoadMode(SceGxmDepthStencilSurface *surface, SceGxmDepthStencilForceLoadMode forceLoad);
SceGxmDepthStencilForceLoadMode sceGxmDepthStencilSurfaceGetForceLoadMode(const SceGxmDepthStencilSurface *surface);
void sceGxmDepthStencilSurfaceSetForceStoreMode(SceGxmDepthStencilSurface *surface, SceGxmDepthStencilForceStoreMode forceStore);
SceGxmDepthStencilForceStoreMode sceGxmDepthStencilSurfaceGetForceStoreMode(const SceGxmDepthStencilSurface *surface);

SceGxmColorSurfaceGammaMode sceGxmColorSurfaceGetGammaMode(const SceGxmColorSurface *surface);
int sceGxmColorSurfaceSetGammaMode(SceGxmColorSurface *surface, SceGxmColorSurfaceGammaMode gammaMode);
SceGxmColorSurfaceDitherMode sceGxmColorSurfaceGetDitherMode(const SceGxmColorSurface *surface);
int sceGxmColorSurfaceSetDitherMode(SceGxmColorSurface *surface, SceGxmColorSurfaceDitherMode ditherMode);

SceGxmDepthStencilFormat sceGxmDepthStencilSurfaceGetFormat(const SceGxmDepthStencilSurface *surface);
unsigned int sceGxmDepthStencilSurfaceGetStrideInSamples(const SceGxmDepthStencilSurface *surface);

int sceGxmProgramCheck(const SceGxmProgram *program);
unsigned int sceGxmProgramGetSize(const SceGxmProgram *program);
SceGxmProgramType sceGxmProgramGetType(const SceGxmProgram *program);
SceBool sceGxmProgramIsDiscardUsed(const SceGxmProgram *program);
SceBool sceGxmProgramIsDepthReplaceUsed(const SceGxmProgram *program);
SceBool sceGxmProgramIsSpriteCoordUsed(const SceGxmProgram *program);
unsigned int sceGxmProgramGetDefaultUniformBufferSize(const SceGxmProgram *program);
unsigned int sceGxmProgramGetParameterCount(const SceGxmProgram *program);

const SceGxmProgramParameter *sceGxmProgramGetParameter(const SceGxmProgram *program, unsigned int index);
const SceGxmProgramParameter *sceGxmProgramFindParameterByName(const SceGxmProgram *program, const char *name);
const SceGxmProgramParameter *sceGxmProgramFindParameterBySemantic(const SceGxmProgram *program, SceGxmParameterSemantic semantic, unsigned int index);
unsigned int sceGxmProgramParameterGetIndex(const SceGxmProgram *program, const SceGxmProgramParameter *parameter);
SceGxmParameterCategory sceGxmProgramParameterGetCategory(const SceGxmProgramParameter *parameter);
const char *sceGxmProgramParameterGetName(const SceGxmProgramParameter *parameter);
SceGxmParameterSemantic sceGxmProgramParameterGetSemantic(const SceGxmProgramParameter *parameter);
unsigned int sceGxmProgramParameterGetSemanticIndex(const SceGxmProgramParameter *parameter);
SceGxmParameterType sceGxmProgramParameterGetType(const SceGxmProgramParameter *parameter);
unsigned int sceGxmProgramParameterGetComponentCount(const SceGxmProgramParameter *parameter);
unsigned int sceGxmProgramParameterGetArraySize(const SceGxmProgramParameter *parameter);
unsigned int sceGxmProgramParameterGetResourceIndex(const SceGxmProgramParameter *parameter);
unsigned int sceGxmProgramParameterGetContainerIndex(const SceGxmProgramParameter *parameter);
SceBool sceGxmProgramParameterIsSamplerCube(const SceGxmProgramParameter *parameter);

const SceGxmProgram *sceGxmFragmentProgramGetProgram(const SceGxmFragmentProgram *fragmentProgram);
const SceGxmProgram *sceGxmVertexProgramGetProgram(const SceGxmVertexProgram *vertexProgram);

int sceGxmShaderPatcherCreate(const SceGxmShaderPatcherParams *params, SceGxmShaderPatcher **shaderPatcher);
int sceGxmShaderPatcherSetUserData(SceGxmShaderPatcher *shaderPatcher, void *userData);
void *sceGxmShaderPatcherGetUserData(SceGxmShaderPatcher *shaderPatcher);
int sceGxmShaderPatcherDestroy(SceGxmShaderPatcher *shaderPatcher);
int sceGxmShaderPatcherRegisterProgram(SceGxmShaderPatcher *shaderPatcher, const SceGxmProgram *programHeader, SceGxmShaderPatcherId *programId);
int sceGxmShaderPatcherUnregisterProgram(SceGxmShaderPatcher *shaderPatcher, SceGxmShaderPatcherId programId);
const SceGxmProgram *sceGxmShaderPatcherGetProgramFromId(SceGxmShaderPatcherId programId);
int sceGxmShaderPatcherSetAuxiliarySurface(SceGxmShaderPatcher *shaderPatcher, unsigned int auxSurfaceIndex, const SceGxmAuxiliarySurface *auxSurface);
int sceGxmShaderPatcherCreateVertexProgram(SceGxmShaderPatcher *shaderPatcher, SceGxmShaderPatcherId programId, const SceGxmVertexAttribute *attributes, unsigned int attributeCount, const SceGxmVertexStream *streams, unsigned int streamCount, SceGxmVertexProgram **vertexProgram);
int sceGxmShaderPatcherCreateFragmentProgram(SceGxmShaderPatcher *shaderPatcher, SceGxmShaderPatcherId programId, SceGxmOutputRegisterFormat outputFormat, SceGxmMultisampleMode multisampleMode, const SceGxmBlendInfo *blendInfo, const SceGxmProgram *vertexProgram, SceGxmFragmentProgram **fragmentProgram);
int sceGxmShaderPatcherAddRefVertexProgram(SceGxmShaderPatcher *shaderPatcher, SceGxmVertexProgram *vertexProgram);
int sceGxmShaderPatcherAddRefFragmentProgram(SceGxmShaderPatcher *shaderPatcher, SceGxmFragmentProgram *fragmentProgram);
int sceGxmShaderPatcherReleaseVertexProgram(SceGxmShaderPatcher *shaderPatcher, SceGxmVertexProgram *vertexProgram);
int sceGxmShaderPatcherReleaseFragmentProgram(SceGxmShaderPatcher *shaderPatcher, SceGxmFragmentProgram *fragmentProgram);
unsigned int sceGxmShaderPatcherGetHostMemAllocated(const SceGxmShaderPatcher *shaderPatcher);
unsigned int sceGxmShaderPatcherGetBufferMemAllocated(const SceGxmShaderPatcher *shaderPatcher);
unsigned int sceGxmShaderPatcherGetVertexUsseMemAllocated(const SceGxmShaderPatcher *shaderPatcher);
unsigned int sceGxmShaderPatcherGetFragmentUsseMemAllocated(const SceGxmShaderPatcher *shaderPatcher);

int sceGxmTextureInitSwizzled(SceGxmTexture *texture, const void *data, SceGxmTextureFormat texFormat, unsigned int width, unsigned int height, unsigned int mipCount);
int sceGxmTextureInitLinear(SceGxmTexture *texture, const void *data, SceGxmTextureFormat texFormat, unsigned int width, unsigned int height, unsigned int mipCount);
int sceGxmTextureInitLinearStrided(SceGxmTexture *texture, const void *data, SceGxmTextureFormat texFormat, unsigned int width, unsigned int height, unsigned int byteStride);
int sceGxmTextureInitTiled(SceGxmTexture *texture, const void *data, SceGxmTextureFormat texFormat, unsigned int width, unsigned int height, unsigned int mipCount);
int sceGxmTextureInitCube(SceGxmTexture *texture, const void *data, SceGxmTextureFormat texFormat, unsigned int width, unsigned int height, unsigned int mipCount);

SceGxmTextureType sceGxmTextureGetType(const SceGxmTexture *texture);

int sceGxmTextureSetMinFilter(SceGxmTexture *texture, SceGxmTextureFilter minFilter);
SceGxmTextureFilter sceGxmTextureGetMinFilter(const SceGxmTexture *texture);

int sceGxmTextureSetMagFilter(SceGxmTexture *texture, SceGxmTextureFilter magFilter);
SceGxmTextureFilter sceGxmTextureGetMagFilter(const SceGxmTexture *texture);

int sceGxmTextureSetMipFilter(SceGxmTexture *texture, SceGxmTextureMipFilter mipFilter);
SceGxmTextureMipFilter sceGxmTextureGetMipFilter(const SceGxmTexture *texture);

int sceGxmTextureSetAnisoMode(SceGxmTexture *texture, SceGxmTextureAnisoMode anisoMode);
SceGxmTextureAnisoMode sceGxmTextureGetAnisoMode(const SceGxmTexture *texture);

int sceGxmTextureSetUAddrMode(SceGxmTexture *texture, SceGxmTextureAddrMode addrMode);
SceGxmTextureAddrMode sceGxmTextureGetUAddrMode(const SceGxmTexture *texture);

int sceGxmTextureSetVAddrMode(SceGxmTexture *texture, SceGxmTextureAddrMode addrMode);
SceGxmTextureAddrMode sceGxmTextureGetVAddrMode(const SceGxmTexture *texture);

int sceGxmTextureSetFormat(SceGxmTexture *texture, SceGxmTextureFormat texFormat);
SceGxmTextureFormat sceGxmTextureGetFormat(const SceGxmTexture *texture);

int sceGxmTextureSetLodBias(SceGxmTexture *texture, unsigned int bias);
unsigned int sceGxmTextureGetLodBias(const SceGxmTexture *texture);

int sceGxmTextureSetStride(SceGxmTexture *texture, unsigned int byteStride);
unsigned int sceGxmTextureGetStride(const SceGxmTexture *texture);

int sceGxmTextureSetWidth(SceGxmTexture *texture, unsigned int width);
unsigned int sceGxmTextureGetWidth(const SceGxmTexture *texture);

int sceGxmTextureSetHeight(SceGxmTexture *texture, unsigned int height);
unsigned int sceGxmTextureGetHeight(const SceGxmTexture *texture);

int sceGxmTextureSetData(SceGxmTexture *texture, const void *data);
void *sceGxmTextureGetData(const SceGxmTexture *texture);

int sceGxmTextureSetMipmapCount(SceGxmTexture *texture, unsigned int mipCount);
unsigned int sceGxmTextureGetMipmapCount(const SceGxmTexture *texture);

int sceGxmTextureSetPalette(SceGxmTexture *texture, const void *paletteData);
void *sceGxmTextureGetPalette(const SceGxmTexture *texture);

SceGxmTextureGammaMode sceGxmTextureGetGammaMode(const SceGxmTexture *texture);
int sceGxmTextureSetGammaMode(SceGxmTexture *texture, SceGxmTextureGammaMode gammaMode);

unsigned int sceGxmGetPrecomputedVertexStateSize(const SceGxmVertexProgram *vertexProgram);
int sceGxmPrecomputedVertexStateInit(SceGxmPrecomputedVertexState *precomputedState, const SceGxmVertexProgram *vertexProgram, void *memBlock);
void sceGxmPrecomputedVertexStateSetDefaultUniformBuffer(SceGxmPrecomputedVertexState *precomputedState, void *defaultBuffer);
void *sceGxmPrecomputedVertexStateGetDefaultUniformBuffer(const SceGxmPrecomputedVertexState *precomputedState);
int sceGxmPrecomputedVertexStateSetAllTextures(SceGxmPrecomputedVertexState *precomputedState, const SceGxmTexture *textures);
int sceGxmPrecomputedVertexStateSetTexture(SceGxmPrecomputedVertexState *precomputedState, unsigned int textureIndex, const SceGxmTexture *texture);
int sceGxmPrecomputedVertexStateSetAllUniformBuffers(SceGxmPrecomputedVertexState *precomputedState, const void * const *bufferDataArray);
int sceGxmPrecomputedVertexStateSetUniformBuffer(SceGxmPrecomputedVertexState *precomputedState, unsigned int bufferIndex, const void *bufferData);
unsigned int sceGxmGetPrecomputedFragmentStateSize(const SceGxmFragmentProgram *fragmentProgram);
int sceGxmPrecomputedFragmentStateInit(SceGxmPrecomputedFragmentState *precomputedState, const SceGxmFragmentProgram *fragmentProgram, void *memBlock);
void sceGxmPrecomputedFragmentStateSetDefaultUniformBuffer(SceGxmPrecomputedFragmentState *precomputedState, void *defaultBuffer);
void *sceGxmPrecomputedFragmentStateGetDefaultUniformBuffer(const SceGxmPrecomputedFragmentState *precomputedState);
int sceGxmPrecomputedFragmentStateSetAllTextures(SceGxmPrecomputedFragmentState *precomputedState, const SceGxmTexture *textureArray);
int sceGxmPrecomputedFragmentStateSetTexture(SceGxmPrecomputedFragmentState *precomputedState, unsigned int textureIndex, const SceGxmTexture *texture);
int sceGxmPrecomputedFragmentStateSetAllUniformBuffers(SceGxmPrecomputedFragmentState *precomputedState, const void * const *bufferDataArray);
int sceGxmPrecomputedFragmentStateSetUniformBuffer(SceGxmPrecomputedFragmentState *precomputedState, unsigned int bufferIndex, const void *bufferData);
int sceGxmPrecomputedFragmentStateSetAllAuxiliarySurfaces(SceGxmPrecomputedFragmentState *precomputedState, const SceGxmAuxiliarySurface *auxSurfaceArray);
unsigned int sceGxmGetPrecomputedDrawSize(const SceGxmVertexProgram *vertexProgram);
int sceGxmPrecomputedDrawInit(SceGxmPrecomputedDraw *precomputedDraw, const SceGxmVertexProgram *vertexProgram, void *memBlock);
int sceGxmPrecomputedDrawSetAllVertexStreams(SceGxmPrecomputedDraw *precomputedDraw, const void * const *streamDataArray);
int sceGxmPrecomputedDrawSetVertexStream(SceGxmPrecomputedDraw *precomputedDraw, unsigned int streamIndex, const void *streamData);
void sceGxmPrecomputedDrawSetParams(SceGxmPrecomputedDraw *precomputedDraw, SceGxmPrimitiveType primType, SceGxmIndexFormat indexType, const void *indexData, unsigned int indexCount);
void sceGxmPrecomputedDrawSetParamsInstanced(SceGxmPrecomputedDraw *precomputedDraw, SceGxmPrimitiveType primType, SceGxmIndexFormat indexType, const void *indexData, unsigned int indexCount, unsigned int indexWrap);

int sceGxmGetRenderTargetMemSizes(const SceGxmRenderTargetParams *params, unsigned int *hostMemSize, unsigned int *driverMemSize);
int sceGxmCreateRenderTarget(const SceGxmRenderTargetParams *params, SceGxmRenderTarget **renderTarget);
int sceGxmRenderTargetGetHostMem(const SceGxmRenderTarget *renderTarget, void **hostMem);
int sceGxmRenderTargetGetDriverMemBlock(const SceGxmRenderTarget *renderTarget, int *driverMemBlock);
int sceGxmDestroyRenderTarget(SceGxmRenderTarget *renderTarget);

int sceGxmSetUniformDataF(void *uniformBuffer, const SceGxmProgramParameter *parameter, unsigned int componentOffset, unsigned int componentCount, const float *sourceData);

#ifdef __cplusplus
}
#endif

#endif /* _PSP2_GXM_ */
