/**
 * \file
 * \brief Header file which defines kernel errors
 *
 * Copyright (C) 2015 PSP2SDK Project
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License version 2.1 as published by the Free Software Foundation
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  021100xFFFFFAEB  USA
 */

#ifndef _COMMON_DIALOG_ERROR_H
#define _COMMON_DIALOG_ERROR_H

#include error.h

enum CommonDialogErrorCodes {
	SCE_COMMON_DIALOG_ERROR_BUSY	= 0x80020401,
	SCE_COMMON_DIALOG_ERROR_NULL	= 0x80020402,
	SCE_COMMON_DIALOG_ERROR_INVALID_ARGUMENT	= 0x80020403,
	SCE_COMMON_DIALOG_ERROR_NOT_RUNNING	= 0x80020404,
	SCE_COMMON_DIALOG_ERROR_NOT_SUPPORTED	= 0x80020405,
	SCE_COMMON_DIALOG_ERROR_ILLEGAL_CALLER_THREAD	= 0x80020406,
	SCE_COMMON_DIALOG_ERROR_NOT_CONFIGURED	= 0x80020407,
	SCE_COMMON_DIALOG_ERROR_NOT_AVAILABLE	= 0x80020408,
	SCE_COMMON_DIALOG_ERROR_NOT_FINISHED	= 0x80020410,
	SCE_COMMON_DIALOG_ERROR_NOT_IN_USE	= 0x80020411,
	SCE_COMMON_DIALOG_ERROR_INVALID_COLOR_FORMAT	= 0x80020420,
	SCE_COMMON_DIALOG_ERROR_INVALID_SURFACE_RESOLUTION	= 0x80020421,
	SCE_COMMON_DIALOG_ERROR_INVALID_SURFACE_STRIDE	= 0x80020422,
	SCE_COMMON_DIALOG_ERROR_INVALID_SURFACE_TYPE	= 0x80020423,
	SCE_COMMON_DIALOG_ERROR_WITHIN_SCENE	= 0x80020424,
	SCE_COMMON_DIALOG_ERROR_IME_IN_USE	= 0x80020430,
	SCE_COMMON_DIALOG_ERROR_INVALID_LANGUAGE	= 0x80020431,
	SCE_COMMON_DIALOG_ERROR_INVALID_ENTER_BUTTON_ASSIGN	= 0x80020432,
	SCE_COMMON_DIALOG_ERROR_INVALID_INFOBAR_PARAM	= 0x80020433,
	SCE_COMMON_DIALOG_ERROR_INVALID_BG_COLOR	= 0x80020434,
	SCE_COMMON_DIALOG_ERROR_INVALID_DIMMER_COLOR	= 0x80020435,
	SCE_COMMON_DIALOG_ERROR_UNEXPECTED_FATAL	= 0x8002047F
}

#endif
